import {demographicValues, demographicFacets, DEMOGRAPHIC_TAXONOMY_VERSION, DEMOGRAPHIC_FILTER_VERSION, GENDERS, AGE_GROUPS} from "@shared/demographicTaxonomy";
import {parseColorFilter, colorFamily, CANONICAL_COLORS, ColorFilterError, COLOR_TAXONOMY_VERSION, COLOR_FILTER_CONTRACT_VERSION} from "@shared/colorTaxonomy";
import type {RequestHandler} from "express";
import pg from "pg";
import {PgCatalogSearchProjectionRepository,type CatalogSearchProjectionRepository,type SearchProjectionFilters} from "../catalogSearchProjection/repository";
import {resolvePublicCatalogSource} from "./policy";

let operationalPool:pg.Pool|undefined;
function repository():CatalogSearchProjectionRepository{operationalPool??=new pg.Pool({connectionString:process.env.AWIN_CURATOR_DATABASE_URL,max:4,application_name:"uppulse_public_catalog"});return new PgCatalogSearchProjectionRepository(operationalPool)}
function enabled(){return resolvePublicCatalogSource(process.env)==="operational"}
function numeric(value:unknown){if(typeof value!=="string"||!value.trim())return undefined;const parsed=Number(value);return Number.isFinite(parsed)?parsed:undefined}
function list(value:unknown){return typeof value==="string"?value.split(",").map(item=>item.trim()).filter(Boolean):undefined}
function offer(row:any){const current=Number(row.current_price),previous=Number(row.previous_price);return{id:row.representative_offer_id,currentPrice:row.current_price,originalPrice:row.previous_price,discountPercent:Number(row.discount_percent),affiliateUrl:row.affiliate_url,marketplaceName:row.merchant_name,sellerName:row.merchant_name,storeLabel:row.merchant_name,freeShipping:false,lastSeenAt:row.source_updated_at,formattedPrice:`R$ ${current.toFixed(2).replace(".",",")}`,formattedOriginalPrice:Number.isFinite(previous)?`R$ ${previous.toFixed(2).replace(".",",")}`:null,demonstrative:false}}
function product(row:any){return{gender:GENDERS.find(x=>x.value===row.gender_normalized)?.value??null,ageGroup:AGE_GROUPS.find(x=>x.value===row.age_group_normalized)?.value??null,demographicTaxonomyVersion:row.demographic_taxonomy_version??null,id:row.product_id,mainName:row.product_name,mainImageUrl:row.primary_image_url,primaryColor:row.normalized_colors?.[0]??null,colors:(row.normalized_colors??[]).map((color:string)=>({name:color,normalized:CANONICAL_COLORS.find(c=>c.label===color)?.id??color,source:"marketplace_variation"})),canonicalColorIds:row.color_taxonomy_version===COLOR_TAXONOMY_VERSION?(row.normalized_colors??[]).flatMap((label:string)=>{const c=CANONICAL_COLORS.find(c=>c.label===label);return c?[c.id]:[];}):[],colorFamilyIds:row.color_taxonomy_version===COLOR_TAXONOMY_VERSION?(row.color_family_ids??[]):[],colorTaxonomyVersion:row.color_taxonomy_version??null,catalogStatus:"published",slug:row.product_id,brand:{name:row.brand_raw,slug:row.brand_normalized},category:{name:row.universe,slug:String(row.universe).toLowerCase()},averageRating:null,totalReviews:0,catalogSource:"operational",demonstrative:false}}
export function operationalFilters(query:any):Omit<SearchProjectionFilters,"page"|"pageSize"|"sort"> {
 const shipping=list(query.frete)??[],types=list(query.tipo)??[],ratings=list(query.avaliacao)??[];
 const genders=demographicValues("genero",query.genero) as SearchProjectionFilters["genders"];
 const ageGroups=demographicValues("idade",query.idade) as SearchProjectionFilters["ageGroups"];
 return {demographicVersion:DEMOGRAPHIC_TAXONOMY_VERSION,available:true,merchants:list(query.merchant),styles:list(query.style),brands:list(query.marca),colors:parseColorFilter(query.cor),genders:genders?.length?genders:undefined,ageGroups:ageGroups?.length?ageGroups:undefined,sizes:list(query.tamanho)?.map(Number).filter(Number.isFinite),activities:list(query.modalidade)?.map((value:string)=>({Corrida:"RUNNING",Caminhada:"WALKING",Treino:"TRAINING",Futebol:"FOOTBALL",Basquete:"BASKETBALL",Skate:"SKATE",Casual:"LIFESTYLE"}[value]??value.toUpperCase())),discountBuckets:list(query.desconto),priceMin:numeric(query.priceMin),priceMax:numeric(query.priceMax),search:typeof query.q==="string"?query.q:typeof query.busca==="string"?query.busca:undefined,impossible:(shipping.length===1&&shipping[0]==="Sim")||(types.length===1&&types[0]==="Acessórios")||ratings.length>0};
}
export function publicFacets(raw:any){const items=(values:any[]|undefined,transform=(value:string)=>value)=>(values??[]).map(item=>({label:transform(String(item.value)),count:Number(item.count)}));const activity=(value:string)=>({RUNNING:"Corrida",WALKING:"Caminhada",TRAINING:"Treino",FOOTBALL:"Futebol",FUTSAL:"Futebol",BASKETBALL:"Basquete",SKATE:"Skate",LIFESTYLE:"Casual"}[value]??value),total=Number(raw.total??0);return{brands:items(raw.brands),colors:(raw.colors??[]).flatMap((item:any)=>{const family=colorFamily(String(item.value));return family?[{value:family.id,label:family.label,count:Number(item.count)}]:[];}),desconto:raw.discounts??{},frete:{Sim:0,"Não":total},sizes:items(raw.sizes),generos:demographicFacets("genero",raw.genders),idades:demographicFacets("idade",raw.ageGroups),modalidades:items(raw.activities,activity),tipos:[{label:"Calçados",count:total},{label:"Acessórios",count:0}],avaliacoes:{},priceMin:Number(raw.priceMin??0),priceMax:Number(raw.priceMax??0),merchants:raw.merchants??[]}}

export function createOperationalPublicCatalogHandlers(getRepository:()=>CatalogSearchProjectionRepository=repository){
 const listHandler:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{if(req.query.audience!==undefined)return res.status(400).json({code:"INVALID_LEGACY_AUDIENCE_FILTER",error:"Use genero e idade."});const pageSize=Math.min(Math.max(numeric(req.query.limit)??21,1),100),offset=Math.max(numeric(req.query.offset)??0,0),requestedSort=typeof req.query.sort==="string"?req.query.sort:"recommended",sorts=new Set(["recommended","discount-desc","discount-asc","price-asc","price-desc","name-asc","brand-asc","recent-desc"]),applied=operationalFilters(req.query),projectionFilters:SearchProjectionFilters={...applied,page:Math.floor(offset/pageSize)+1,pageSize,sort:(sorts.has(requestedSort)?requestedSort:"recommended") as SearchProjectionFilters["sort"]},repo=getRepository(),[rows,total,rawFacets]=await Promise.all([repo.listProducts(projectionFilters),repo.countProducts(applied),repo.getFacets(applied)]);res.setHeader("X-UpPulse-Catalog-Source","operational");res.json({demographicFilterVersion:DEMOGRAPHIC_FILTER_VERSION,demographicTaxonomyVersion:DEMOGRAPHIC_TAXONOMY_VERSION,colorTaxonomyVersion:COLOR_TAXONOMY_VERSION,colorFilterContractVersion:COLOR_FILTER_CONTRACT_VERSION,total,limit:pageSize,offset,catalogSource:"operational",serverDriven:true,demonstrative:false,facets:publicFacets({...rawFacets,total}),products:rows.map((row:any)=>({...product(row),offersCount:1,bestOffer:offer(row)}))})}catch(error){if(error instanceof ColorFilterError)return res.status(400).json({code:error.code,error:"Seleção de cor inválida. Remova a seleção e escolha uma família de cor."});console.error("Operational public catalog failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Catálogo operacional temporariamente indisponível"})}};
 const detail:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{const rows=await getRepository().getProduct(req.params.id);if(!rows.length)return res.status(404).json({error:"Produto não encontrado"});const first:any=rows[0];res.setHeader("X-UpPulse-Catalog-Source","operational");res.json({...product(first),images:first.primary_image_url?[{url:first.primary_image_url,isPrimary:true}]:[],offers:rows.map(offer)})}catch(error){console.error("Operational product detail failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Catálogo operacional temporariamente indisponível"})}};
 const click:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{const row:any=await getRepository().getOffer(req.params.offerId);if(!row?.affiliate_url)return res.status(404).json({error:"Oferta não encontrada"});const target=new URL(row.affiliate_url);if(target.protocol!=="https:"&&target.protocol!=="http:")return res.status(404).json({error:"Oferta não encontrada"});res.redirect(row.affiliate_url)}catch(error){console.error("Operational affiliate click failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Oferta temporariamente indisponível"})}};
 return{list:listHandler,detail,click};
}
const handlers=createOperationalPublicCatalogHandlers();
export const operationalPublicCatalogHandler=handlers.list;
export const operationalPublicProductDetailHandler=handlers.detail;
export const operationalPublicAffiliateClickHandler=handlers.click;
