import type { RequestHandler } from "express";
import pg from "pg";
import { PgCatalogSearchProjectionRepository, type CatalogSearchProjectionRepository, type SearchProjectionFilters } from "../catalogSearchProjection/repository";
import { resolvePublicCatalogSource } from "./policy";

let operationalPool: pg.Pool | undefined;
function repository(): CatalogSearchProjectionRepository { operationalPool ??= new pg.Pool({connectionString:process.env.AWIN_CURATOR_DATABASE_URL,max:4,application_name:"uppulse_public_catalog"}); return new PgCatalogSearchProjectionRepository(operationalPool); }
function enabled(){return resolvePublicCatalogSource(process.env)==="operational"}
function numeric(value:unknown){if(typeof value!=="string"||!value.trim())return undefined;const parsed=Number(value);return Number.isFinite(parsed)?parsed:undefined}
function offer(row:any){const current=Number(row.current_price),previous=Number(row.previous_price);return{id:row.representative_offer_id,currentPrice:row.current_price,originalPrice:row.previous_price,discountPercent:Number(row.discount_percent),affiliateUrl:row.affiliate_url,marketplaceName:row.merchant_name,sellerName:row.merchant_name,freeShipping:false,lastSeenAt:row.source_updated_at,formattedPrice:`R$ ${current.toFixed(2).replace(".",",")}`,formattedOriginalPrice:Number.isFinite(previous)?`R$ ${previous.toFixed(2).replace(".",",")}`:null}}
function product(row:any){return{id:row.product_id,mainName:row.product_name,mainImageUrl:row.primary_image_url,primaryColor:row.normalized_colors?.[0]??null,colors:(row.normalized_colors??[]).map((color:string)=>({name:color,normalized:color,source:"catalog_projection",confidence:"high"})),catalogStatus:"published",slug:row.product_id,brand:{name:row.brand_raw,slug:row.brand_normalized},category:{name:row.universe,slug:String(row.universe).toLowerCase()},averageRating:null,totalReviews:0}}

export function createOperationalPublicCatalogHandlers(getRepository:()=>CatalogSearchProjectionRepository=repository){
 const list:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{const limit=Math.min(Math.max(numeric(req.query.limit)??100,1),5000),offset=Math.max(numeric(req.query.offset)??0,0),requestedSort=typeof req.query.sort==="string"?req.query.sort:"recommended",sorts=new Set(["recommended","discount-desc","discount-asc","price-asc","price-desc","name-asc","brand-asc"]);const filters:SearchProjectionFilters={page:Math.floor(offset/limit)+1,pageSize:limit,sort:(sorts.has(requestedSort)?requestedSort:"recommended") as SearchProjectionFilters["sort"],available:true,brand:typeof req.query.brand==="string"?req.query.brand:undefined,merchant:typeof req.query.merchant==="string"?req.query.merchant:undefined,audience:typeof req.query.audience==="string"?req.query.audience:undefined,style:typeof req.query.style==="string"?req.query.style:undefined,activity:typeof req.query.activity==="string"?req.query.activity:undefined,size:numeric(req.query.size),discountMin:numeric(req.query.discountMin),discountMax:numeric(req.query.discountMax),priceMin:numeric(req.query.priceMin),priceMax:numeric(req.query.priceMax)};const countFilters:any={...filters};delete countFilters.page;delete countFilters.pageSize;delete countFilters.sort;const repo=getRepository(),[rows,total]=await Promise.all([repo.listProducts(filters),repo.countProducts(countFilters)]);res.setHeader("X-UpPulse-Catalog-Source","operational");res.json({total,products:rows.map((row:any)=>({...product(row),offersCount:1,bestOffer:offer(row)}))})}catch(error){console.error("Operational public catalog failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Catálogo operacional temporariamente indisponível"})}};
 const detail:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{const rows=await getRepository().getProduct(req.params.id);if(!rows.length)return res.status(404).json({error:"Produto não encontrado"});const first:any=rows[0];res.setHeader("X-UpPulse-Catalog-Source","operational");res.json({...product(first),images:first.primary_image_url?[{url:first.primary_image_url,isPrimary:true}]:[],offers:rows.map(offer)})}catch(error){console.error("Operational product detail failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Catálogo operacional temporariamente indisponível"})}};
 const click:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{const row:any=await getRepository().getOffer(req.params.offerId);if(!row?.affiliate_url)return res.status(404).json({error:"Oferta não encontrada"});const target=new URL(row.affiliate_url);if(target.protocol!=="https:"&&target.protocol!=="http:")return res.status(404).json({error:"Oferta não encontrada"});res.redirect(row.affiliate_url)}catch(error){console.error("Operational affiliate click failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Oferta temporariamente indisponível"})}};
 return{list,detail,click};
}
const handlers=createOperationalPublicCatalogHandlers();
export const operationalPublicCatalogHandler=handlers.list;
export const operationalPublicProductDetailHandler=handlers.detail;
export const operationalPublicAffiliateClickHandler=handlers.click;
