import type {RequestHandler} from "express";
import pg from "pg";
import {PgCatalogSearchProjectionRepository,type CatalogSearchProjectionRepository,type SearchProjectionFilters} from "../catalogSearchProjection/repository";
import {resolvePublicCatalogSource} from "./policy";

let operationalPool:pg.Pool|undefined;
function repository():CatalogSearchProjectionRepository{operationalPool??=new pg.Pool({connectionString:process.env.AWIN_CURATOR_DATABASE_URL,max:4,application_name:"uppulse_public_catalog"});return new PgCatalogSearchProjectionRepository(operationalPool)}
function enabled(){return resolvePublicCatalogSource(process.env)==="operational"}
function numeric(value:unknown){if(typeof value!=="string"||!value.trim())return undefined;const parsed=Number(value);return Number.isFinite(parsed)?parsed:undefined}
function list(value:unknown){return typeof value==="string"?value.split(",").map(item=>item.trim()).filter(Boolean):undefined}
function offer(row:any){const current=Number(row.current_price),previous=Number(row.previous_price);return{id:row.representative_offer_id,currentPrice:row.current_price,originalPrice:row.previous_price,discountPercent:Number(row.discount_percent),affiliateUrl:row.affiliate_url,marketplaceName:row.merchant_name,sellerName:row.merchant_name,storeLabel:row.merchant_name,freeShipping:false,lastSeenAt:row.source_updated_at,formattedPrice:`R$ ${current.toFixed(2).replace(".",",")}`,formattedOriginalPrice:Number.isFinite(previous)?`R$ ${previous.toFixed(2).replace(".",",")}`:null,demonstrative:false}}
function product(row:any){return{id:row.product_id,mainName:row.product_name,mainImageUrl:row.primary_image_url,primaryColor:row.normalized_colors?.[0]??null,colors:(row.normalized_colors??[]).map((color:string)=>({name:color,normalized:color,source:"catalog_projection",confidence:"high"})),catalogStatus:"published",slug:row.product_id,brand:{name:row.brand_raw,slug:row.brand_normalized},category:{name:row.universe,slug:String(row.universe).toLowerCase()},averageRating:null,totalReviews:0,catalogSource:"operational",demonstrative:false}}
function filters(query:any):Omit<SearchProjectionFilters,"page"|"pageSize"|"sort">{const ages=list(query.idade)??[],shipping=list(query.frete)??[],types=list(query.tipo)??[],ratings=list(query.avaliacao)??[],audiences=list(query.genero)?.map((value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase())??[];if(ages.length===1&&ages[0]==="Infantil")audiences.push("INFANTIL");return{available:true,merchant:typeof query.merchant==="string"?query.merchant:undefined,brands:list(query.marca),colors:list(query.cor),audiences:audiences.length?Array.from(new Set(audiences)):undefined,excludeAudiences:ages.length===1&&ages[0]==="Adulto"?["INFANTIL"]:undefined,sizes:list(query.tamanho)?.map(Number).filter(Number.isFinite),activities:list(query.modalidade)?.map((value:string)=>({Corrida:"RUNNING",Caminhada:"WALKING",Treino:"TRAINING",Futebol:"FOOTBALL",Basquete:"BASKETBALL",Skate:"SKATE",Casual:"LIFESTYLE"}[value]??value.toUpperCase())),discountBuckets:list(query.desconto),priceMin:numeric(query.priceMin),priceMax:numeric(query.priceMax),search:typeof query.q==="string"?query.q:typeof query.busca==="string"?query.busca:undefined,impossible:(shipping.length===1&&shipping[0]==="Sim")||(types.length===1&&types[0]==="Acessórios")||ratings.length>0}}
function publicFacets(raw:any){const items=(values:any[]|undefined,transform=(value:string)=>value)=>(values??[]).map(item=>({label:transform(String(item.value)),count:Number(item.count)}));const audience=(value:string)=>({MASCULINO:"Masculino",FEMININO:"Feminino",UNISSEX:"Unissex",INFANTIL:"Infantil"}[value]??value);const activity=(value:string)=>({RUNNING:"Corrida",WALKING:"Caminhada",TRAINING:"Treino",FOOTBALL:"Futebol",FUTSAL:"Futebol",BASKETBALL:"Basquete",SKATE:"Skate",LIFESTYLE:"Casual"}[value]??value),total=Number(raw.total??0),children=Number(raw.audiences?.find((item:any)=>item.value==="INFANTIL")?.count??0);return{brands:items(raw.brands),colors:(raw.colors??[]).map((item:any)=>({value:String(item.value),label:String(item.value),count:Number(item.count)})),desconto:raw.discounts??{},frete:{Sim:0,"Não":total},sizes:items(raw.sizes),generos:items(raw.audiences?.filter((item:any)=>item.value!=="INFANTIL"),audience),idades:[{label:"Adulto",count:Math.max(0,total-children)},{label:"Infantil",count:children}],modalidades:items(raw.activities,activity),tipos:[{label:"Calçados",count:total},{label:"Acessórios",count:0}],avaliacoes:{},priceMin:Number(raw.priceMin??0),priceMax:Number(raw.priceMax??0),merchants:raw.merchants??[]}}

export function createOperationalPublicCatalogHandlers(getRepository:()=>CatalogSearchProjectionRepository=repository){
 const listHandler:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{const pageSize=Math.min(Math.max(numeric(req.query.limit)??21,1),100),offset=Math.max(numeric(req.query.offset)??0,0),requestedSort=typeof req.query.sort==="string"?req.query.sort:"recommended",sorts=new Set(["recommended","discount-desc","discount-asc","price-asc","price-desc","name-asc","brand-asc","recent-desc"]),applied=filters(req.query),projectionFilters:SearchProjectionFilters={...applied,page:Math.floor(offset/pageSize)+1,pageSize,sort:(sorts.has(requestedSort)?requestedSort:"recommended") as SearchProjectionFilters["sort"]},repo=getRepository(),[rows,total,rawFacets]=await Promise.all([repo.listProducts(projectionFilters),repo.countProducts(applied),repo.getFacets(applied)]);res.setHeader("X-UpPulse-Catalog-Source","operational");res.json({total,limit:pageSize,offset,catalogSource:"operational",serverDriven:true,demonstrative:false,facets:publicFacets({...rawFacets,total}),products:rows.map((row:any)=>({...product(row),offersCount:1,bestOffer:offer(row)}))})}catch(error){console.error("Operational public catalog failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Catálogo operacional temporariamente indisponível"})}};
 const detail:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{const rows=await getRepository().getProduct(req.params.id);if(!rows.length)return res.status(404).json({error:"Produto não encontrado"});const first:any=rows[0];res.setHeader("X-UpPulse-Catalog-Source","operational");res.json({...product(first),images:first.primary_image_url?[{url:first.primary_image_url,isPrimary:true}]:[],offers:rows.map(offer)})}catch(error){console.error("Operational product detail failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Catálogo operacional temporariamente indisponível"})}};
 const click:RequestHandler=async(req,res,next)=>{if(!enabled())return next();try{const row:any=await getRepository().getOffer(req.params.offerId);if(!row?.affiliate_url)return res.status(404).json({error:"Oferta não encontrada"});const target=new URL(row.affiliate_url);if(target.protocol!=="https:"&&target.protocol!=="http:")return res.status(404).json({error:"Oferta não encontrada"});res.redirect(row.affiliate_url)}catch(error){console.error("Operational affiliate click failed",error instanceof Error?error.message:"unknown");res.status(503).json({error:"Oferta temporariamente indisponível"})}};
 return{list:listHandler,detail,click};
}
const handlers=createOperationalPublicCatalogHandlers();
export const operationalPublicCatalogHandler=handlers.list;
export const operationalPublicProductDetailHandler=handlers.detail;
export const operationalPublicAffiliateClickHandler=handlers.click;
