export type PublicCatalogSource = "demo" | "operational";
export type PublicationState = "DRAFT" | "PUBLISHED" | "PAUSED" | "EXPIRED";
export type PublicationEvent = "publish" | "pause" | "resume" | "refresh" | "expire";
const transitions: Record<PublicationState, Partial<Record<PublicationEvent, PublicationState>>> = { DRAFT:{publish:"PUBLISHED",refresh:"DRAFT",expire:"EXPIRED"}, PUBLISHED:{pause:"PAUSED",refresh:"PUBLISHED",expire:"EXPIRED"}, PAUSED:{resume:"PUBLISHED",refresh:"PAUSED",expire:"EXPIRED"}, EXPIRED:{refresh:"DRAFT"} };
export function transitionPublication(state:PublicationState,event:PublicationEvent){return transitions[state][event]??null}
export type PublicOfferEligibility={catalogState:string;available:boolean;currentPrice:number;previousPrice:number;currency:string;affiliateUrl:string|null;productName:string;brand:string;primaryImageUrl:string|null;sourceUpdatedAt:Date};
export function isPublicOfferEligible(o:PublicOfferEligibility,now:Date,maxAgeDays=3){const age=now.getTime()-o.sourceUpdatedAt.getTime();return o.catalogState==="CATALOG_ELIGIBLE"&&o.available&&o.currentPrice>0&&o.previousPrice>o.currentPrice&&o.currency==="BRL"&&Boolean(o.affiliateUrl)&&Boolean(o.productName.trim())&&Boolean(o.brand.trim())&&Boolean(o.primaryImageUrl)&&age>=0&&age<=maxAgeDays*86_400_000}
export function resolvePublicCatalogSource(env:NodeJS.ProcessEnv):PublicCatalogSource{return env.UPPULSE_PUBLIC_CATALOG_SOURCE==="operational"&&env.UPPULSE_PUBLIC_CATALOG_APPROVED==="true"&&Boolean(env.AWIN_CURATOR_DATABASE_URL)?"operational":"demo"}
// Quality/completeness lead; offer strength is capped, so discount alone cannot dominate.
export function publicRank(i:{available:boolean;brand:string;productName:string;primaryImageUrl:string|null;normalizedSizes:number[];normalizedColors:string[];activities:string[];discountPercent:number;sourceUpdatedAt:Date},now:Date){const completeness=(i.brand.trim()?10:0)+(i.productName.trim()?10:0)+(i.primaryImageUrl?15:0)+(i.normalizedSizes.length?10:0)+(i.normalizedColors.length?5:0),relevance=Math.min(i.activities.length,2)*5,offer=(i.available?20:0)+Math.min(Math.max(i.discountPercent,0),50)*.2,age=Math.max(0,(now.getTime()-i.sourceUpdatedAt.getTime())/86_400_000);return completeness+relevance+offer+Math.max(0,10-Math.min(age,10))}
