import {useMemo,useState} from "react";import {useQuery} from "@tanstack/react-query";import type {CatalogPreviewFacetsResponse,CatalogPreviewResponse} from "@shared/catalogPreview";import CatalogPreviewCard from "@/components/CatalogPreviewCard";import {Button} from "@/components/ui/button";
const selects=[['brand','Marca','brands'],['audience','Público','audiences'],['size','Tamanho','sizes'],['style','Style','styles'],['activity','Activity','activities'],['merchant','Merchant','merchants']] as const;
export default function CatalogPreview(){
 const [page,setPage]=useState(1),[filters,setFilters]=useState<Record<string,string>>({sort:"discount-desc"});const params=useMemo(()=>new URLSearchParams({page:String(page),pageSize:"24",...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))}).toString(),[page,filters]);
 const query=useQuery<CatalogPreviewResponse>({queryKey:[`/api/catalog-preview/products?${params}`]});const facetQuery=useQuery<CatalogPreviewFacetsResponse>({queryKey:["/api/catalog-preview/facets"]});const change=(key:string,value:string)=>{setFilters(v=>({...v,[key]:value}));setPage(1)};
 return <main className="min-h-screen bg-slate-100 p-4 md:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6"><div className="inline-block rounded bg-amber-300 px-3 py-1 text-sm font-black">PREVIEW INTERNO — NÃO PUBLICADO</div><h1 className="mt-3 text-3xl font-black">Catálogo Dafiti — Preview</h1><p className="text-slate-600">{query.data?`${query.data.pagination.totalProducts.toLocaleString("pt-BR")} produtos elegíveis`:"Carregando catálogo operacional…"}</p></header>
 <section className="mb-6 grid gap-3 rounded-lg border bg-white p-4 sm:grid-cols-2 lg:grid-cols-4">{selects.map(([key,label,facet])=><label key={key} className="text-xs font-semibold">{label}<select aria-label={label} value={filters[key]??""} onChange={e=>change(key,e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Todos</option>{facetQuery.data?.facets[facet].map(x=><option key={x.value} value={x.value}>{x.value} ({x.count})</option>)}</select></label>)}<label className="text-xs font-semibold">Desconto mínimo<input aria-label="Desconto mínimo" type="number" min="0" max="100" value={filters.discountMin??""} onChange={e=>change("discountMin",e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label className="text-xs font-semibold">Preço mínimo<input aria-label="Preço mínimo" type="number" min="0" value={filters.priceMin??""} onChange={e=>change("priceMin",e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label className="text-xs font-semibold">Preço máximo<input aria-label="Preço máximo" type="number" min="0" value={filters.priceMax??""} onChange={e=>change("priceMax",e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label className="text-xs font-semibold">Ordenação<select aria-label="Ordenação" value={filters.sort} onChange={e=>change("sort",e.target.value)} className="mt-1 w-full rounded border p-2"><option value="discount-desc">Maior desconto</option><option value="discount-asc">Menor desconto</option><option value="price-asc">Menor preço</option><option value="price-desc">Maior preço</option><option value="name-asc">Nome A-Z</option><option value="brand-asc">Marca A-Z</option></select></label><Button variant="outline" onClick={()=>{setFilters({sort:"discount-desc"});setPage(1)}}>Limpar filtros</Button></section>
 {query.isLoading&&<div className="py-20 text-center">Carregando produtos…</div>}{query.isError&&<div className="rounded border border-red-200 bg-red-50 p-6 text-red-800">Erro técnico ao carregar o preview. Tente novamente.</div>}{query.data&&!query.data.items.length&&<div className="rounded border bg-white p-10 text-center">Nenhum produto encontrado com estes filtros.</div>}{query.data&&<><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{query.data.items.map(p=><CatalogPreviewCard key={p.id} product={p}/>)}</section><nav className="mt-8 flex items-center justify-center gap-4"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</Button><span>Página {page} de {query.data.pagination.totalPages}</span><Button variant="outline" disabled={page>=query.data.pagination.totalPages} onClick={()=>setPage(p=>p+1)}>Próxima</Button></nav></>}</div></main>;
}
