import {classifyAudience,type Audience} from "../integrations/awin/dafitiCuration";
import {CATALOG_CLASSIFIER_VERSION,CATALOG_NORMALIZER_VERSION} from "../integrations/awin/operationalCatalog";
export const SEARCH_PROJECTION_VERSION="uppulse-catalog-search-v1";
export type ProjectionSourceRow={productId:string;providerId:string;merchantId:string;productName:string;brandRaw:string|null;audienceRaw:string|null;catalogState:string;universe:string;style:string;activities:string[];classifierVersion:string;variantId:string;sizeNormalized:number|null;sizeStatus:string;colorNormalized:string[]|null;colorStatus:string;normalizerVersion:string;offerId:string;currentPrice:number;previousPrice:number;discountPercent:number;currency:string;inStock:boolean;promotionStatus:string;primaryImageUrl:string|null;feedId:string|null;sourceUpdatedAt:string};
export type CatalogSearchProjectionRow={productId:string;providerId:string;merchantId:string;representativeOfferId:string;productName:string;brandRaw:string;brandNormalized:string;audienceRaw:string|null;audienceNormalized:Audience;universe:string;style:string;activities:string[];currentPrice:number;previousPrice:number;discountPercent:number;currency:string;available:boolean;normalizedSizes:number[];normalizedColors:string[];primaryImageUrl:string|null;catalogState:"CATALOG_ELIGIBLE";classifierVersion:string;normalizerVersion:string;sourceSnapshot:string;projectionVersion:string;sourceUpdatedAt:string;projectedAt:string};
export type ProjectionBuildReport={rows:CatalogSearchProjectionRow[];stats:{sourceRows:number;projectedRows:number;brands:number;audiences:Record<string,number>;sizes:number;colors:number;styles:Record<string,number>;activities:Record<string,number>;merchants:number;missing:{brand:number;image:number;offer:number};conflicts:{brand:number;audience:number;classifierVersion:number;normalizerVersion:number}}};
const normalizeBrand=(value:string)=>value.normalize("NFKC").replace(/\s+/g," ").trim().toLocaleLowerCase("pt-BR");
const distinct=<T>(values:T[]):T[]=>Array.from(new Set(values));
const increment=(target:Record<string,number>,key:string)=>target[key]=(target[key]??0)+1;
export function chooseRepresentativeOffer(rows:ProjectionSourceRow[]){return rows.filter(r=>r.promotionStatus==="PROMOTION_CONFIRMED"&&r.inStock&&r.currentPrice>0&&r.previousPrice>r.currentPrice).slice().sort((a,b)=>b.discountPercent-a.discountPercent||a.currentPrice-b.currentPrice||a.offerId.localeCompare(b.offerId))[0]??null;}
export function buildCatalogSearchProjection(source:ProjectionSourceRow[],projectedAt=new Date().toISOString()):ProjectionBuildReport{
 const groups=new Map<string,ProjectionSourceRow[]>();
 for(const row of source)if(row.catalogState==="CATALOG_ELIGIBLE"){const key=`${row.productId}:${row.merchantId}`;groups.set(key,[...(groups.get(key)??[]),row]);}
 const rows:CatalogSearchProjectionRow[]=[],missing={brand:0,image:0,offer:0},conflicts={brand:0,audience:0,classifierVersion:0,normalizerVersion:0};
 for(const group of Array.from(groups.values())){
  const first=group[0];
  const brands=distinct(group.map(r=>r.brandRaw?.trim()).filter((x):x is string=>Boolean(x)));
  const audiences=distinct(group.map(r=>r.audienceRaw?.trim()).filter((x):x is string=>Boolean(x)));
  const classifiers=distinct(group.map(r=>r.classifierVersion)),normalizers=distinct(group.map(r=>r.normalizerVersion));
  const offer=chooseRepresentativeOffer(group);if(!brands.length)missing.brand++;if(!first.primaryImageUrl)missing.image++;if(!offer){missing.offer++;continue}if(brands.length>1)conflicts.brand++;if(audiences.length>1)conflicts.audience++;if(classifiers.length>1)conflicts.classifierVersion++;if(normalizers.length>1)conflicts.normalizerVersion++;
  const brand=brands[0]??"";if(!brand)continue;const updated=group.map(r=>Date.parse(r.sourceUpdatedAt)).filter(Number.isFinite);const sourceUpdatedAt=updated.length?new Date(Math.max(...updated)).toISOString():projectedAt;
  rows.push({productId:first.productId,providerId:first.providerId,merchantId:first.merchantId,representativeOfferId:offer.offerId,productName:first.productName,brandRaw:brand,brandNormalized:normalizeBrand(brand),audienceRaw:audiences[0]??null,audienceNormalized:classifyAudience({suitableFor:audiences[0],name:first.productName}),universe:first.universe,style:first.style,activities:distinct(group.flatMap(r=>r.activities)).sort(),currentPrice:offer.currentPrice,previousPrice:offer.previousPrice,discountPercent:offer.discountPercent,currency:offer.currency,available:offer.inStock,normalizedSizes:distinct(group.filter(r=>r.sizeStatus==="NORMALIZED_SAFE"&&r.sizeNormalized!=null).map(r=>r.sizeNormalized as number)).sort((a,b)=>a-b),normalizedColors:distinct(group.filter(r=>r.colorStatus==="NORMALIZED_SAFE").flatMap(r=>r.colorNormalized??[])).sort(),primaryImageUrl:first.primaryImageUrl,catalogState:"CATALOG_ELIGIBLE",classifierVersion:classifiers[0]??CATALOG_CLASSIFIER_VERSION,normalizerVersion:normalizers[0]??CATALOG_NORMALIZER_VERSION,sourceSnapshot:distinct(group.map(r=>r.feedId).filter((x):x is string=>Boolean(x))).sort().join(",")||"unknown",projectionVersion:SEARCH_PROJECTION_VERSION,sourceUpdatedAt,projectedAt});
 }
 const audiences:Record<string,number>={},styles:Record<string,number>={},activities:Record<string,number>={};for(const row of rows){increment(audiences,row.audienceNormalized);increment(styles,row.style);for(const value of row.activities)increment(activities,value)}
 return{rows,stats:{sourceRows:source.length,projectedRows:rows.length,brands:new Set(rows.map(r=>r.brandNormalized)).size,audiences,sizes:new Set(rows.flatMap(r=>r.normalizedSizes)).size,colors:new Set(rows.flatMap(r=>r.normalizedColors)).size,styles,activities,merchants:new Set(rows.map(r=>r.merchantId)).size,missing,conflicts}};
}
