import type pg from "pg";
import type { CatalogPreviewSort } from "@shared/catalogPreview";

export type SearchProjectionFilters={externalMerchantId?:string;merchant?:string;brands?:string[];colors?:string[];audiences?:string[];excludeAudiences?:string[];sizes?:number[];activities?:string[];styles?:string[];discountBuckets?:string[];priceMin?:number;priceMax?:number;available?:boolean;search?:string;impossible?:boolean;page:number;pageSize:number;sort:CatalogPreviewSort|"recent-desc"};
type AppliedFilters=Omit<SearchProjectionFilters,"page"|"pageSize"|"sort">;
export interface CatalogSearchProjectionRepository{listProducts(filters:SearchProjectionFilters):Promise<Record<string,unknown>[]>;countProducts(filters:AppliedFilters):Promise<number>;getProduct(productId:string):Promise<Record<string,unknown>[]>;getOffer(offerId:string):Promise<Record<string,unknown>|null>;getFacets(filters:AppliedFilters):Promise<Record<string,unknown>>}
type Queryable=Pick<pg.Pool,"query">;
const fold=(value:string)=>value.normalize("NFKC").trim().toLocaleLowerCase("pt-BR");
const searchTerms=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLocaleLowerCase("pt-BR").split(/\s+/).filter(Boolean);

function where(input:AppliedFilters){const clauses=[`c.catalog_state='CATALOG_ELIGIBLE'`],params:unknown[]=[];const add=(v:unknown)=>{params.push(v);return `$${params.length}`};if(input.impossible)clauses.push("false");
 if(input.externalMerchantId)clauses.push(`m.external_merchant_id=${add(input.externalMerchantId)}`);if(input.merchant)clauses.push(`m.name=${add(input.merchant)}`);
 if(input.brands?.length)clauses.push(`c.brand_normalized = ANY(${add(input.brands.map(fold))}::text[])`);if(input.colors?.length)clauses.push(`c.normalized_colors && ${add(input.colors)}::text[]`);if(input.audiences?.length)clauses.push(`c.audience_normalized = ANY(${add(input.audiences)}::text[])`);if(input.excludeAudiences?.length)clauses.push(`NOT (c.audience_normalized = ANY(${add(input.excludeAudiences)}::text[]))`);if(input.sizes?.length)clauses.push(`c.normalized_sizes && ${add(input.sizes)}::numeric[]`);if(input.activities?.length)clauses.push(`c.activities && ${add(input.activities)}::text[]`);if(input.styles?.length)clauses.push(`c.style = ANY(${add(input.styles)}::text[])`);
 if(input.discountBuckets?.length){const parts:string[]=[];for(const bucket of input.discountBuckets){if(bucket==="50% ou mais")parts.push("c.discount_percent>=50");else if(bucket==="40% - 49%")parts.push("(c.discount_percent>=40 AND c.discount_percent<50)");else if(bucket==="30% - 39%")parts.push("(c.discount_percent>=30 AND c.discount_percent<40)");else if(bucket==="20% - 29%")parts.push("(c.discount_percent>=20 AND c.discount_percent<30)");else if(bucket==="Até 19%")parts.push("(c.discount_percent>0 AND c.discount_percent<20)")}clauses.push(parts.length?`(${parts.join(" OR ")})`:"false")}
 if(input.priceMin!=null)clauses.push(`c.current_price>=${add(input.priceMin)}`);if(input.priceMax!=null)clauses.push(`c.current_price<=${add(input.priceMax)}`);if(input.available!=null)clauses.push(`c.available=${add(input.available)}`);
 if(input.search)for(const term of searchTerms(input.search))clauses.push(`translate(lower(c.product_name || ' ' || c.brand_raw || ' ' || m.name),'áàâãäéèêëíìîïóòôõöúùûüç','aaaaaeeeeiiiiooooouuuuc') LIKE ${add(`%${term}%`)}`);
 return{sql:clauses.join(" AND "),params};}

export class PgCatalogSearchProjectionRepository implements CatalogSearchProjectionRepository{constructor(private db:Queryable){}
 async listProducts(f:SearchProjectionFilters){const q=where(f),recommended=`((CASE WHEN c.available THEN 20 ELSE 0 END)+(CASE WHEN c.primary_image_url IS NOT NULL THEN 15 ELSE 0 END)+(CASE WHEN cardinality(c.normalized_sizes)>0 THEN 10 ELSE 0 END)+(CASE WHEN cardinality(c.normalized_colors)>0 THEN 5 ELSE 0 END)+LEAST(cardinality(c.activities),2)*5+LEAST(GREATEST(c.discount_percent,0),50)*0.2+GREATEST(0,10-LEAST(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-c.source_updated_at))/86400,10))) DESC`,sort:Record<SearchProjectionFilters["sort"],string>={recommended,"discount-desc":"c.discount_percent DESC","discount-asc":"c.discount_percent ASC","price-asc":"c.current_price ASC","price-desc":"c.current_price DESC","name-asc":"c.product_name ASC","brand-asc":"c.brand_normalized ASC","recent-desc":"c.source_updated_at DESC"};q.params.push(f.pageSize,(f.page-1)*f.pageSize);return(await this.db.query(`SELECT c.*,o.affiliate_url,m.name merchant_name FROM catalog_search_products c JOIN commerce_merchants m ON m.id=c.merchant_id JOIN offers o ON o.id=c.representative_offer_id WHERE ${q.sql} ORDER BY ${sort[f.sort]},c.product_id,c.merchant_id LIMIT $${q.params.length-1} OFFSET $${q.params.length}`,q.params)).rows;}
 async countProducts(f:AppliedFilters){const q=where(f);return Number((await this.db.query(`SELECT count(*)::int total FROM catalog_search_products c JOIN commerce_merchants m ON m.id=c.merchant_id WHERE ${q.sql}`,q.params)).rows[0]?.total??0);}
 async getProduct(productId:string){return(await this.db.query(`SELECT c.*,o.affiliate_url,m.name merchant_name FROM catalog_search_products c JOIN commerce_merchants m ON m.id=c.merchant_id JOIN offers o ON o.id=c.representative_offer_id WHERE c.catalog_state='CATALOG_ELIGIBLE' AND c.available=true AND c.product_id=$1 ORDER BY c.merchant_id`,[productId])).rows;}
 async getOffer(offerId:string){return(await this.db.query(`SELECT c.product_id,c.representative_offer_id,o.affiliate_url,m.name merchant_name FROM catalog_search_products c JOIN commerce_merchants m ON m.id=c.merchant_id JOIN offers o ON o.id=c.representative_offer_id WHERE c.catalog_state='CATALOG_ELIGIBLE' AND c.available=true AND c.representative_offer_id=$1`,[offerId])).rows[0]??null;}
 async getFacets(f:AppliedFilters){const q=where(f);return(await this.db.query(`WITH base AS MATERIALIZED (SELECT c.*,m.name merchant_name FROM catalog_search_products c JOIN commerce_merchants m ON m.id=c.merchant_id WHERE ${q.sql}) SELECT jsonb_build_object('brands',COALESCE((SELECT jsonb_agg(x) FROM(SELECT brand_raw value,count(*)::int count FROM base GROUP BY brand_raw ORDER BY count DESC,brand_raw)x),'[]'::jsonb),'audiences',COALESCE((SELECT jsonb_agg(x) FROM(SELECT audience_normalized value,count(*)::int count FROM base GROUP BY audience_normalized ORDER BY count DESC,value)x),'[]'::jsonb),'sizes',COALESCE((SELECT jsonb_agg(x) FROM(SELECT size::text value,count(*)::int count FROM base CROSS JOIN LATERAL unnest(normalized_sizes) size GROUP BY size ORDER BY size)x),'[]'::jsonb),'styles',COALESCE((SELECT jsonb_agg(x) FROM(SELECT style value,count(*)::int count FROM base GROUP BY style ORDER BY count DESC,style)x),'[]'::jsonb),'activities',COALESCE((SELECT jsonb_agg(x) FROM(SELECT activity value,count(*)::int count FROM base CROSS JOIN LATERAL unnest(activities) activity GROUP BY activity ORDER BY count DESC,activity)x),'[]'::jsonb),'merchants',COALESCE((SELECT jsonb_agg(x) FROM(SELECT merchant_name value,count(*)::int count FROM base GROUP BY merchant_name ORDER BY count DESC,merchant_name)x),'[]'::jsonb),'colors',COALESCE((SELECT jsonb_agg(x) FROM(SELECT color value,count(*)::int count FROM base CROSS JOIN LATERAL unnest(normalized_colors) color GROUP BY color ORDER BY count DESC,color LIMIT 50)x),'[]'::jsonb),'discounts',jsonb_build_object('50% ou mais',(SELECT count(*)::int FROM base WHERE discount_percent>=50),'40% - 49%',(SELECT count(*)::int FROM base WHERE discount_percent>=40 AND discount_percent<50),'30% - 39%',(SELECT count(*)::int FROM base WHERE discount_percent>=30 AND discount_percent<40),'20% - 29%',(SELECT count(*)::int FROM base WHERE discount_percent>=20 AND discount_percent<30),'Até 19%',(SELECT count(*)::int FROM base WHERE discount_percent>0 AND discount_percent<20)),'priceMin',COALESCE((SELECT floor(min(current_price))::int FROM base),0),'priceMax',COALESCE((SELECT ceil(max(current_price))::int FROM base),0)) facets`,q.params)).rows[0]?.facets??{};}}
