import type pg from "pg";
import type { CatalogPreviewSort } from "@shared/catalogPreview";
export type SearchProjectionFilters={externalMerchantId?:string;merchant?:string;brand?:string;audience?:string;size?:number;discountMin?:number;discountMax?:number;priceMin?:number;priceMax?:number;style?:string;activity?:string;available?:boolean;page:number;pageSize:number;sort:CatalogPreviewSort};
export interface CatalogSearchProjectionRepository{listProducts(filters:SearchProjectionFilters):Promise<Record<string,unknown>[]>;countProducts(filters:Omit<SearchProjectionFilters,"page"|"pageSize"|"sort">):Promise<number>;getFacets(externalMerchantId?:string):Promise<Record<string,unknown>>}
type Queryable=Pick<pg.Pool,"query">;
function where(input:Omit<SearchProjectionFilters,"page"|"pageSize"|"sort">){const clauses=[`c.catalog_state='CATALOG_ELIGIBLE'`],params:unknown[]=[];const add=(v:unknown)=>{params.push(v);return `$${params.length}`};if(input.externalMerchantId)clauses.push(`m.external_merchant_id=${add(input.externalMerchantId)}`);if(input.merchant)clauses.push(`m.name=${add(input.merchant)}`);if(input.brand)clauses.push(`c.brand_normalized=${add(input.brand.normalize("NFKC").trim().toLocaleLowerCase("pt-BR"))}`);if(input.audience)clauses.push(`c.audience_normalized=${add(input.audience)}`);if(input.size!=null)clauses.push(`c.normalized_sizes @> ARRAY[${add(input.size)}::numeric]`);if(input.discountMin!=null)clauses.push(`c.discount_percent>=${add(input.discountMin)}`);if(input.discountMax!=null)clauses.push(`c.discount_percent<=${add(input.discountMax)}`);if(input.priceMin!=null)clauses.push(`c.current_price>=${add(input.priceMin)}`);if(input.priceMax!=null)clauses.push(`c.current_price<=${add(input.priceMax)}`);if(input.style)clauses.push(`c.style=${add(input.style)}`);if(input.activity)clauses.push(`c.activities @> ARRAY[${add(input.activity)}::text]`);if(input.available!=null)clauses.push(`c.available=${add(input.available)}`);return{sql:clauses.join(" AND "),params};}
export class PgCatalogSearchProjectionRepository implements CatalogSearchProjectionRepository{constructor(private db:Queryable){}
 async listProducts(f:SearchProjectionFilters){const q=where(f),sort:Record<CatalogPreviewSort,string>={"discount-desc":"c.discount_percent DESC","discount-asc":"c.discount_percent ASC","price-asc":"c.current_price ASC","price-desc":"c.current_price DESC","name-asc":"c.product_name ASC","brand-asc":"c.brand_normalized ASC"};q.params.push(f.pageSize,(f.page-1)*f.pageSize);return(await this.db.query(`SELECT c.*,o.affiliate_url,m.name merchant_name FROM catalog_search_products c JOIN commerce_merchants m ON m.id=c.merchant_id JOIN offers o ON o.id=c.representative_offer_id WHERE ${q.sql} ORDER BY ${sort[f.sort]},c.product_id LIMIT $${q.params.length-1} OFFSET $${q.params.length}`,q.params)).rows;}
 async countProducts(f:Omit<SearchProjectionFilters,"page"|"pageSize"|"sort">){const q=where(f);return Number((await this.db.query(`SELECT count(*)::int total FROM catalog_search_products c JOIN commerce_merchants m ON m.id=c.merchant_id WHERE ${q.sql}`,q.params)).rows[0]?.total??0);}
 async getFacets(externalMerchantId?:string){const params=externalMerchantId?[externalMerchantId]:[],filter=externalMerchantId?`WHERE m.external_merchant_id=$1`:"";return(await this.db.query(`WITH base AS MATERIALIZED (SELECT c.*,m.name merchant_name FROM catalog_search_products c JOIN commerce_merchants m ON m.id=c.merchant_id ${filter}) SELECT jsonb_build_object('brands',(SELECT jsonb_agg(x) FROM(SELECT brand_raw value,count(*)::int count FROM base GROUP BY brand_raw ORDER BY count DESC,brand_raw)x),'audiences',(SELECT jsonb_agg(x) FROM(SELECT audience_normalized value,count(*)::int count FROM base GROUP BY audience_normalized ORDER BY count DESC,1)x),'sizes',(SELECT jsonb_agg(x) FROM(SELECT size::text value,count(*)::int count FROM base CROSS JOIN LATERAL unnest(normalized_sizes) size GROUP BY size ORDER BY size)x),'styles',(SELECT jsonb_agg(x) FROM(SELECT style value,count(*)::int count FROM base GROUP BY style ORDER BY count DESC,style)x),'activities',(SELECT jsonb_agg(x) FROM(SELECT activity value,count(*)::int count FROM base CROSS JOIN LATERAL unnest(activities) activity GROUP BY activity ORDER BY count DESC,activity)x),'merchants',(SELECT jsonb_agg(x) FROM(SELECT merchant_name value,count(*)::int count FROM base GROUP BY merchant_name ORDER BY count DESC,merchant_name)x),'colors',(SELECT jsonb_agg(x) FROM(SELECT color value,count(*)::int count FROM base CROSS JOIN LATERAL unnest(normalized_colors) color GROUP BY color ORDER BY count DESC,color LIMIT 50)x)) facets`,params)).rows[0]?.facets??{};}}
