import {demographicValues, DEMOGRAPHIC_TAXONOMY_VERSION} from "@shared/demographicTaxonomy";
import pg from "pg";
import type{CatalogPreviewFacets,CatalogPreviewProduct,CatalogPreviewSort}from "@shared/catalogPreview";
import{PgCatalogSearchProjectionRepository,type SearchProjectionFilters}from "../catalogSearchProjection/repository";
export type PreviewFilters={brand?:string;genero?:string;idade?:string;size?:string;discountMin?:number;discountMax?:number;priceMin?:number;priceMax?:number;style?:string;activity?:string;merchant?:string;available?:boolean;sort:CatalogPreviewSort;page:number;pageSize:number};
export type QueryTimings={productsMs:number;countMs:number;detailsMs:number};
export interface CatalogPreviewRepository{list(filters:PreviewFilters):Promise<{items:CatalogPreviewProduct[];pagination:{page:number;pageSize:number;totalProducts:number;totalPages:number};queryMs:number;roundTrips:number;queryTimings:QueryTimings}>;facets(filters?:PreviewFilters):Promise<{facets:CatalogPreviewFacets;queryMs:number;cached:boolean;roundTrips:number}>}
const emptyFacets=():CatalogPreviewFacets=>({brands:[],genders:[],ageGroups:[],sizes:[],styles:[],activities:[],merchants:[],colors:[]});
export class PgCatalogPreviewRepository implements CatalogPreviewRepository{private pool:pg.Pool;private projection:PgCatalogSearchProjectionRepository;constructor(connectionString:string){this.pool=new pg.Pool({connectionString,max:4,application_name:"uppulse_catalog_preview"});this.projection=new PgCatalogSearchProjectionRepository(this.pool)}
 async list(f:PreviewFilters){const started=performance.now(),projected:SearchProjectionFilters={page:f.page,pageSize:f.pageSize,sort:f.sort,brands:f.brand?[f.brand]:undefined,genders:demographicValues("genero",f.genero) as SearchProjectionFilters["genders"],ageGroups:demographicValues("idade",f.idade) as SearchProjectionFilters["ageGroups"],demographicVersion:DEMOGRAPHIC_TAXONOMY_VERSION,sizes:f.size==null?undefined:[Number(f.size)],priceMin:f.priceMin,priceMax:f.priceMax,styles:f.style?[f.style]:undefined,activities:f.activity?[f.activity]:undefined,merchant:f.merchant,available:f.available},countFilters:any={...projected};delete countFilters.page;delete countFilters.pageSize;delete countFilters.sort;const tp=performance.now(),productsPromise=this.projection.listProducts(projected).then(rows=>({rows,ms:performance.now()-tp})),tc=performance.now(),countPromise=this.projection.countProducts(countFilters).then(total=>({total,ms:performance.now()-tc})),[products,count]=await Promise.all([productsPromise,countPromise]);const items:CatalogPreviewProduct[]=products.rows.map((r:any)=>({id:r.product_id,brand:r.brand_raw,name:r.product_name,description:null,gender:r.gender_normalized??null,ageGroup:r.age_group_normalized??null,demographicTaxonomyVersion:r.demographic_taxonomy_version??null,taxonomy:{universe:r.universe,style:r.style,activities:r.activities??[],confidence:"PROJECTED"},pricing:{currentPrice:Number(r.current_price),previousPrice:Number(r.previous_price),discountPercent:Number(r.discount_percent),currency:r.currency},variants:[],normalizedSizes:(r.normalized_sizes??[]).map(Number),normalizedColors:r.normalized_colors??[],colorFamilyIds:r.color_family_ids??[],colorTaxonomyVersion:r.color_taxonomy_version??null,primaryImage:r.primary_image_url,images:r.primary_image_url?[r.primary_image_url]:[],merchant:{id:r.merchant_id,name:r.merchant_name},affiliateUrl:r.affiliate_url,representativeOfferId:r.representative_offer_id}));return{items,pagination:{page:f.page,pageSize:f.pageSize,totalProducts:count.total,totalPages:Math.ceil(count.total/f.pageSize)},queryMs:+(performance.now()-started).toFixed(1),roundTrips:2,queryTimings:{productsMs:+products.ms.toFixed(1),countMs:+count.ms.toFixed(1),detailsMs:0}}}
 async facets(f?:PreviewFilters){
  const started=performance.now();
  const raw=await this.projection.getFacets({demographicVersion:DEMOGRAPHIC_TAXONOMY_VERSION,genders:demographicValues("genero",f?.genero) as SearchProjectionFilters["genders"],ageGroups:demographicValues("idade",f?.idade) as SearchProjectionFilters["ageGroups"],brands:f?.brand?[f.brand]:undefined,sizes:f?.size?[Number(f.size)]:undefined,styles:f?.style?[f.style]:undefined,activities:f?.activity?[f.activity]:undefined,merchant:f?.merchant,priceMin:f?.priceMin,priceMax:f?.priceMax,available:f?.available});
  const {audiences:legacyAudience,...publicFacets}=raw;
  return {facets:{...emptyFacets(),...publicFacets} as CatalogPreviewFacets,queryMs:+(performance.now()-started).toFixed(1),cached:false,roundTrips:1};
 }
}
