import pg from "pg";
import { classifyAudience,classifyDafitiScope,curateVariant,DAFITI_MERCHANT_ID,priceShape,suspiciousSize } from "../server/integrations/awin/dafitiCuration";

type Row=Record<string,any>; const count=(m:Record<string,number>,k:string)=>m[k]=(m[k]??0)+1;
const stats=(xs:number[])=>{const a=[...xs].sort((x,y)=>x-y),q=(p:number)=>a.length?a[Math.floor((a.length-1)*p)]:null;return {min:a[0]??null,mean:a.length?+(a.reduce((x,y)=>x+y,0)/a.length).toFixed(2):null,median:q(.5),p25:q(.25),p75:q(.75),p90:q(.9),max:a.at(-1)??null}};
const bucket=(n:number,edges:number[])=>String(edges.find(e=>n<e)??"max");

async function main(){
 const command=process.argv[2]??"summary"; if(!["summary","brands","discounts","prices","sizes","review"].includes(command)) throw new Error("Uso: awin:dafiti-curation -- summary|brands|discounts|prices|sizes|review");
 const cs=process.env.AWIN_CURATOR_DATABASE_URL; if(!cs) throw new Error("AWIN_CURATOR_DATABASE_URL é obrigatória; DATABASE_URL não é usada implicitamente");
 const started=performance.now(),pool=new pg.Pool({connectionString:cs,max:1}),client=await pool.connect(); let queries=0;
 const query=async(sql:string,v:unknown[]=[])=>{queries++;return client.query(sql,v)};
 try { await query("BEGIN READ ONLY"); await query("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ");
  const before=(await query(`SELECT (SELECT count(*) FROM products WHERE catalog_status='published')::int published,(SELECT count(*) FROM users)::int users,(SELECT count(*) FROM user_favorites)::int favorites,(SELECT count(*) FROM external_product_identities e JOIN commerce_merchants m ON m.id=e.merchant_id WHERE m.external_merchant_id=$1 AND (e.publication_state<>'staging' OR e.active))::int unsafe_products,(SELECT count(*) FROM product_variants v JOIN commerce_merchants m ON m.id=v.merchant_id WHERE m.external_merchant_id=$1 AND v.active)::int active_variants,(SELECT count(*) FROM offers o JOIN commerce_merchants m ON m.id=o.merchant_id WHERE m.external_merchant_id=$1 AND (o.active OR o.status<>'paused'))::int unsafe_offers`,[DAFITI_MERCHANT_ID])).rows[0];
  const rows=(await query(`SELECT p.id product_id,p.main_name name,p.detailed_description description,e.external_product_key,e.merchant_product_page_url,v.id variant_id,v.external_variant_key,v.size,v.colour,v.attributes,o.id offer_id,o.external_offer_key,o.current_price::float8,o.original_price::float8,o.currency,o.in_stock,o.status,o.active offer_active,(o.affiliate_url IS NOT NULL AND o.affiliate_url<>'') affiliate_available,(o.original_url IS NOT NULL AND o.original_url<>'') merchant_url_available,pe.discount_percent::float8,pe.old_price::float8,pe.current_price::float8 evidence_current,(pe.old_price-pe.current_price)::float8 saving_amount,r.raw_payload->>'brand_name' brand,r.raw_payload->>'merchant_category' merchant_category,r.raw_payload->>'merchant_product_category_path' category_path,r.raw_payload->>'merchant_product_second_category' second_category,r.raw_payload->>'merchant_product_third_category' third_category,r.raw_payload->>'product_type' product_type,r.raw_payload->>'Fashion:category' fashion_category,r.raw_payload->>'Fashion:suitable_for' suitable_for,(SELECT count(*)::int FROM product_images i WHERE i.product_id=p.id) image_count FROM commerce_merchants m JOIN external_product_identities e ON e.merchant_id=m.id JOIN products p ON p.id=e.product_id JOIN product_variants v ON v.product_id=p.id AND v.merchant_id=m.id JOIN offers o ON o.variant_id=v.id AND o.merchant_id=m.id JOIN offer_promotion_evidence pe ON pe.offer_id=o.id LEFT JOIN commerce_raw_feed_items r ON r.merchant_id=m.id AND r.merchant_product_id=v.merchant_product_id WHERE m.external_merchant_id=$1 ORDER BY p.id,v.id`,[DAFITI_MERCHANT_ID])).rows as Row[];
  const imageRows=(await query(`SELECT i.product_id,i.url,i.is_primary,i.sort_order FROM product_images i JOIN external_product_identities e ON e.product_id=i.product_id JOIN commerce_merchants m ON m.id=e.merchant_id WHERE m.external_merchant_id=$1 ORDER BY i.product_id,i.sort_order,i.url`,[DAFITI_MERCHANT_ID])).rows as Row[];
  const products=new Map<string,Row[]>(); for(const r of rows) products.set(r.product_id,[...(products.get(r.product_id)??[]),r]);
  const status:Record<string,number>={},reviewReasons:Record<string,number>={},ineligibleReasons:Record<string,number>={},scopes:Record<string,number>={},audiencesP:Record<string,number>={},audiencesO:Record<string,number>={},sizes:Record<string,number>={},colours:Record<string,number>={},sizeCounts:Record<string,number>={},priceShapes={SINGLE_PRICE:0,MULTIPLE_CURRENT_PRICES:0,MULTIPLE_OLD_PRICES:0,MULTIPLE_DISCOUNTS:0};
  const eligible:Row[]=[]; const brandMap=new Map<string,Row[]>(); const reviewSamples:any[]=[]; let extreme50=0,extreme60=0,extreme70=0,extremeConsistent=0,extremeReview=0;
  for(const [id,rs] of Array.from(products)){ const first=rs[0],scope=classifyDafitiScope({merchantCategory:first.merchant_category,categoryPath:first.category_path,secondCategory:first.second_category,thirdCategory:first.third_category,productType:first.product_type,fashionCategory:first.fashion_category,name:first.name,description:first.description}); const audience=classifyAudience({suitableFor:first.suitable_for,categoryPath:first.category_path,name:first.name}); count(scopes,scope.scope);count(audiencesP,audience); for(const r of rs)count(audiencesO,audience);
    const decisions=rs.map(r=>curateVariant({scope,currentPrice:r.current_price,oldPrice:r.old_price,discountPercent:r.discount_percent,inStock:r.in_stock,affiliateAvailable:r.affiliate_available,merchantUrlAvailable:r.merchant_url_available,imageAvailable:r.image_count>0,brand:r.brand,name:r.name,size:r.size,currency:r.currency,identityCollision:false,extremeConsistent:Math.abs(r.discount_percent-((r.old_price-r.current_price)/r.old_price*100))<=.11}));
    const good=decisions.map((d,i)=>[d,rs[i]] as const).filter(([d])=>d.status!=="INELIGIBLE"); let finalStatus:string,reasons:string[];
    if(!good.length){finalStatus="INELIGIBLE";reasons=Array.from(new Set(decisions.flatMap(d=>d.reasons)));} else { const review=Array.from(new Set(good.flatMap(([d])=>d.status==="NEEDS_REVIEW"?d.reasons:[]))); const shape=priceShape(good.map(([,r])=>({currentPrice:r.current_price,oldPrice:r.old_price,discountPercent:r.discount_percent}))); if(shape.multipleCurrentPrices||shape.multipleOldPrices||shape.multipleDiscounts)review.push("multiple_price_policy_required"); finalStatus=review.length?"NEEDS_REVIEW":"ELIGIBLE";reasons=review.length?review:["eligible"]; eligible.push(first); brandMap.set(first.brand,[...(brandMap.get(first.brand)??[]),...good.map(([,r])=>r)]); if(shape.singlePrice)priceShapes.SINGLE_PRICE++;if(shape.multipleCurrentPrices)priceShapes.MULTIPLE_CURRENT_PRICES++;if(shape.multipleOldPrices)priceShapes.MULTIPLE_OLD_PRICES++;if(shape.multipleDiscounts)priceShapes.MULTIPLE_DISCOUNTS++; const max=Math.max(...good.map(([,r])=>r.discount_percent));if(max>=50)extreme50++;if(max>=60)extreme60++;if(max>=70)extreme70++;if(max>=50){const consistent=good.every(([,r])=>Math.abs(r.discount_percent-((r.old_price-r.current_price)/r.old_price*100))<=.11);if(consistent)extremeConsistent++;else extremeReview++;} }
    count(status,finalStatus);for(const reason of reasons) if(finalStatus==="NEEDS_REVIEW")count(reviewReasons,reason);else if(finalStatus==="INELIGIBLE")count(ineligibleReasons,reason); if(finalStatus!=="ELIGIBLE"&&reviewSamples.length<50)reviewSamples.push({productId:id,name:first.name,brand:first.brand,status:finalStatus,reasons,scope:scope.scope,evidence:scope.evidence});
    for(const r of rs){count(sizes,String(r.size??""));count(colours,String(r.colour??""));} count(sizeCounts,String(new Set(rs.map(r=>r.size).filter(Boolean)).size>=8?"8+":new Set(rs.map(r=>r.size).filter(Boolean)).size));
  }
  const eligibleIds=new Set(eligible.map(r=>r.product_id)),eligibleRows=rows.filter(r=>eligibleIds.has(r.product_id)); const productPrices=eligible.map(p=>Math.min(...(products.get(p.product_id)??[]).map(r=>r.current_price))),productDiscounts=eligible.map(p=>Math.max(...(products.get(p.product_id)??[]).map(r=>r.discount_percent)));
  const thresholds=[5,10,15,20,25,30,40,50,60,70].map(min=>{const ps=eligible.filter(p=>Math.max(...products.get(p.product_id)!.map(r=>r.discount_percent))>=min),ids=new Set(ps.map(p=>p.product_id)),rr=eligibleRows.filter(r=>ids.has(r.product_id));return {minimumPercent:min,products:ps.length,variants:rr.length,offers:rr.length,brands:new Set(ps.map(p=>p.brand)).size,averagePrice:+(ps.reduce((s,p)=>s+Math.min(...products.get(p.product_id)!.map(r=>r.current_price)),0)/Math.max(ps.length,1)).toFixed(2),averageDiscount:+(ps.reduce((s,p)=>s+Math.max(...products.get(p.product_id)!.map(r=>r.discount_percent)),0)/Math.max(ps.length,1)).toFixed(2)}});
  const brands=Array.from(brandMap).map(([brand,rr])=>{const ids=Array.from(new Set(rr.map(r=>r.product_id))),prices=ids.map(id=>Math.min(...products.get(id)!.map(r=>r.current_price))),discounts=ids.map(id=>Math.max(...products.get(id)!.map(r=>r.discount_percent))),scopeDist:Record<string,number>={};for(const id of ids)count(scopeDist,classifyDafitiScope({merchantCategory:products.get(id)![0].merchant_category,name:products.get(id)![0].name}).scope);return {brand,products:ids.length,variants:rr.length,offers:rr.length,price:stats(prices),discount:stats(discounts),scope:scopeDist}}).sort((a,b)=>b.products-a.products||a.brand.localeCompare(b.brand));
  const imgs=imageRows.filter(r=>eligibleIds.has(r.product_id)),imgPer=new Map<string,number>();let invalidImages=0;const imageHosts:Record<string,number>={};for(const i of imgs){imgPer.set(i.product_id,(imgPer.get(i.product_id)??0)+1);try{count(imageHosts,new URL(i.url).hostname)}catch{invalidImages++}} const imageDistribution:Record<string,number>={};for(const n of Array.from(imgPer.values()))count(imageDistribution,n>=5?"5+":String(n));
  const priceDistribution:Record<string,number>={};for(const n of productPrices)count(priceDistribution,bucket(n,[100,200,300,400,500,700,1000,1500])); const suspicious=Object.entries(sizes).filter(([v])=>suspiciousSize(v));
  const duplicate=(key:(r:Row)=>string)=>{const m=new Map<string,Set<string>>();for(const p of eligible){const k=key(p);if(k)m.set(k,new Set([...Array.from(m.get(k)??[]),p.product_id]));}const groups=Array.from(m).filter(([,ids])=>ids.size>1);return {groups:groups.length,products:groups.reduce((s,[,ids])=>s+ids.size,0),samples:groups.slice(0,10).map(([key,ids])=>({key:key.slice(0,120),products:ids.size}))}};
  const report={generatedAt:new Date().toISOString(),merchantId:DAFITI_MERCHANT_ID,baseline:before,analysed:{products:products.size,variants:rows.length,offers:rows.length},curation:{status,reviewReasons,ineligibleReasons,scope:scopes,audience:{products:audiencesP,offers:audiencesO}},discounts:{stats:stats(productDiscounts),thresholds,extreme:{gte50:extreme50,gte60:extreme60,gte70:extreme70,EXTREME_BUT_CONSISTENT:extremeConsistent,NEEDS_REVIEW:extremeReview}},prices:{stats:stats(productPrices),distribution:priceDistribution},brands:{count:brands.length,quality:{empty:brands.filter(b=>!b.brand?.trim()).length,caseAliases:Object.keys(Object.fromEntries(brands.map(b=>[b.brand.toLocaleLowerCase("pt-BR"),1]))).length<brands.length},top50:brands.slice(0,50)},sizes:{distinct:Object.keys(sizes).length,distribution:sizes,productsByDistinctSizeCount:sizeCounts,empty:sizes[""]??0,suspicious},colours:{distinct:Object.keys(colours).length,top:Object.entries(colours).sort((a,b)=>b[1]-a[1]).slice(0,100),empty:colours[""]??0,compound:Object.entries(colours).filter(([v])=>/[\/,+-]|\s.+\s/.test(v)).length},images:{total:imgs.length,perProduct:stats(Array.from(imgPer.values())),distribution:imageDistribution,invalid:invalidImages,duplicateUrls:imgs.length-new Set(imgs.map(i=>i.url)).size,hosts:imageHosts,primaryCandidates:imgs.filter(i=>i.is_primary).length},priceShapes,duplicates:{brandAndName:duplicate(p=>`${p.brand}|${String(p.name).trim().toLocaleLowerCase("pt-BR")}`),name:duplicate(p=>String(p.name).trim().toLocaleLowerCase("pt-BR")),description:duplicate(p=>String(p.description??"").trim()),image:duplicate(p=>imageRows.find(i=>i.product_id===p.product_id)?.url??"")},reviewSamples,performance:{elapsedMs:+(performance.now()-started).toFixed(2),queries:queries+1,rssBytes:process.memoryUsage().rss,rowsMaterialized:rows.length}};
  const selected=command==="summary"?report:command==="brands"?report.brands:command==="discounts"?report.discounts:command==="prices"?report.prices:command==="sizes"?report.sizes:{curation:report.curation,extreme:report.discounts.extreme,duplicates:report.duplicates,samples:report.reviewSamples}; console.log(JSON.stringify(selected,null,2)); await query("ROLLBACK");
 } finally {client.release();await pool.end();}
}
void main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1});
