import pg from "pg";

if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL ausente");
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, max: 1 });
const merchantExternalId = "17697";
const rows = async (sql: string, values: unknown[] = []) => (await pool.query(sql, values)).rows;
const one = async (sql: string, values: unknown[] = []) => (await rows(sql, values))[0];

const productSummary = `WITH dm AS (SELECT id FROM commerce_merchants WHERE external_merchant_id=$1),
br AS (SELECT DISTINCT ON (v.product_id) v.product_id,r.raw_payload->>'brand_name' brand,r.raw_payload->>'merchant_category' category FROM product_variants v JOIN dm ON dm.id=v.merchant_id JOIN commerce_raw_feed_items r ON r.merchant_id=v.merchant_id AND r.merchant_product_id=v.merchant_product_id ORDER BY v.product_id,r.last_seen_at DESC),
po AS (SELECT DISTINCT ON (o.product_id) o.product_id,o.original_price::numeric old_price,o.current_price::numeric current_price,((o.original_price-o.current_price)/o.original_price*100)::numeric discount FROM offers o JOIN dm ON dm.id=o.merchant_id ORDER BY o.product_id,((o.original_price-o.current_price)/o.original_price*100) DESC,o.current_price),
va AS (SELECT v.product_id,count(*)::int variants,array_agg(DISTINCT v.size ORDER BY v.size) FILTER (WHERE v.size IS NOT NULL) sizes,array_agg(DISTINCT v.colour ORDER BY v.colour) FILTER (WHERE v.colour IS NOT NULL) colours FROM product_variants v JOIN dm ON dm.id=v.merchant_id GROUP BY v.product_id),
im AS (SELECT i.product_id,count(*)::int images FROM product_images i JOIN external_product_identities e ON e.product_id=i.product_id JOIN dm ON dm.id=e.merchant_id GROUP BY i.product_id)
SELECT p.id,p.main_name name,p.catalog_status publication_state,p.usage_type,br.brand,br.category,po.old_price,po.current_price,po.discount,va.variants,va.sizes,va.colours,COALESCE(im.images,0)::int images,p.detailed_description IS NOT NULL has_description,true affiliate_link_available,true merchant_link_available,'PROMOTION_CONFIRMED' promotion_status FROM products p JOIN br ON br.product_id=p.id JOIN po ON po.product_id=p.id JOIN va ON va.product_id=p.id LEFT JOIN im ON im.product_id=p.id`;

async function main() {
  const baseline = await one("SELECT (SELECT count(*)::int FROM products) products_total,(SELECT count(*)::int FROM products WHERE catalog_status=$1) products_published,(SELECT count(*)::int FROM products WHERE catalog_status=$2) products_draft,(SELECT count(*)::int FROM offers) offers_total,(SELECT count(*)::int FROM product_variants) variants_total,(SELECT count(*)::int FROM commerce_providers) providers,(SELECT count(*)::int FROM commerce_merchants) merchants,(SELECT count(*)::int FROM commerce_feeds) feeds,(SELECT count(*)::int FROM users) users,(SELECT count(*)::int FROM user_favorites) favorites", ["published", "draft"]);
  const dafiti = await one("SELECT (SELECT count(*)::int FROM external_product_identities e JOIN commerce_merchants m ON m.id=e.merchant_id WHERE m.external_merchant_id=$1) products,(SELECT count(*)::int FROM product_variants v JOIN commerce_merchants m ON m.id=v.merchant_id WHERE m.external_merchant_id=$1) variants,(SELECT count(*)::int FROM offers o JOIN commerce_merchants m ON m.id=o.merchant_id WHERE m.external_merchant_id=$1) offers,(SELECT count(*)::int FROM commerce_raw_feed_items r JOIN commerce_merchants m ON m.id=r.merchant_id WHERE m.external_merchant_id=$1) raw,(SELECT count(*)::int FROM product_images i JOIN external_product_identities e ON e.product_id=i.product_id JOIN commerce_merchants m ON m.id=e.merchant_id WHERE m.external_merchant_id=$1) images,(SELECT count(*)::int FROM offer_promotion_evidence pe JOIN offers o ON o.id=pe.offer_id JOIN commerce_merchants m ON m.id=o.merchant_id WHERE m.external_merchant_id=$1) evidence", [merchantExternalId]);
  const isolation = await rows("SELECT p.code,m.external_merchant_id,m.name,(SELECT count(*)::int FROM external_product_identities e WHERE e.merchant_id=m.id) products,(SELECT count(*)::int FROM product_variants v WHERE v.merchant_id=m.id) variants,(SELECT count(*)::int FROM offers o WHERE o.merchant_id=m.id) offers FROM commerce_merchants m JOIN commerce_providers p ON p.id=m.provider_id ORDER BY m.external_merchant_id");
  const feeds = await rows("SELECT f.external_feed_id,count(r.id)::int raw_items FROM commerce_feeds f JOIN commerce_merchants m ON m.id=f.merchant_id LEFT JOIN commerce_raw_feed_items r ON r.feed_id=f.id WHERE m.external_merchant_id=$1 GROUP BY f.external_feed_id ORDER BY f.external_feed_id", [merchantExternalId]);
  const safety = await one("SELECT (SELECT count(*)::int FROM external_product_identities e JOIN commerce_merchants m ON m.id=e.merchant_id WHERE m.external_merchant_id=$1 AND (e.publication_state<>$2 OR e.active)) unsafe_products,(SELECT count(*)::int FROM product_variants v JOIN commerce_merchants m ON m.id=v.merchant_id WHERE m.external_merchant_id=$1 AND v.active) active_variants,(SELECT count(*)::int FROM offers o JOIN commerce_merchants m ON m.id=o.merchant_id WHERE m.external_merchant_id=$1 AND (o.active OR o.status<>$3)) unsafe_offers,(SELECT count(*)::int FROM offers o JOIN commerce_merchants m ON m.id=o.merchant_id WHERE m.external_merchant_id=$1 AND (o.affiliate_url IS NULL OR o.original_url IS NULL OR o.current_price<=0 OR o.original_price<=o.current_price OR NOT o.in_stock)) offers_missing_minimum,(SELECT count(*)::int FROM products p JOIN external_product_identities e ON e.product_id=p.id JOIN commerce_merchants m ON m.id=e.merchant_id WHERE m.external_merchant_id=$1 AND (p.detailed_description IS NULL OR p.main_image_url IS NULL)) products_missing_content", [merchantExternalId, "staging", "paused"]);
  const evidence = await one("SELECT count(*)::int total,count(*) FILTER (WHERE pe.promotion_status=$2 AND pe.promotion_evidence_type=$3 AND pe.evidence_source=$4 AND pe.old_price>pe.current_price AND pe.current_price>0)::int valid,min(pe.discount_percent)::numeric min,avg(pe.discount_percent)::numeric mean,percentile_cont(0.5) WITHIN GROUP (ORDER BY pe.discount_percent)::numeric median,max(pe.discount_percent)::numeric max FROM offer_promotion_evidence pe JOIN offers o ON o.id=pe.offer_id JOIN commerce_merchants m ON m.id=o.merchant_id WHERE m.external_merchant_id=$1", [merchantExternalId, "PROMOTION_CONFIRMED", "OLD_PRICE_GT_CURRENT_PRICE", "AWIN_DAFITI_FEED"]);
  const brandDistribution = await rows(`SELECT brand,count(*)::int products,sum(variants)::int variants,min(current_price)::numeric min_price,max(current_price)::numeric max_price,avg(discount)::numeric avg_discount,max(discount)::numeric max_discount FROM (${productSummary}) s GROUP BY brand ORDER BY products DESC,brand`, [merchantExternalId]);
  const discountDistribution = await rows(`SELECT CASE WHEN discount<10 THEN '0–9%' WHEN discount<20 THEN '10–19%' WHEN discount<30 THEN '20–29%' WHEN discount<40 THEN '30–39%' WHEN discount<50 THEN '40–49%' WHEN discount<60 THEN '50–59%' WHEN discount<70 THEN '60–69%' ELSE '70%+' END bucket,count(*)::int products,sum(variants)::int variants FROM (${productSummary}) s GROUP BY 1 ORDER BY min(discount)`, [merchantExternalId]);
  const priceDistribution = await rows(`SELECT CASE WHEN current_price<200 THEN 'até R$199' WHEN current_price<300 THEN 'R$200–299' WHEN current_price<400 THEN 'R$300–399' WHEN current_price<500 THEN 'R$400–499' WHEN current_price<700 THEN 'R$500–699' WHEN current_price<1000 THEN 'R$700–999' ELSE 'R$1.000+' END bucket,count(*)::int products,sum(variants)::int variants FROM (${productSummary}) s GROUP BY 1 ORDER BY min(current_price)`, [merchantExternalId]);
  const usageDistribution = await rows(`SELECT usage_type,count(*)::int products FROM (${productSummary}) s GROUP BY usage_type ORDER BY products DESC`, [merchantExternalId]);
  const productStats = await one(`SELECT min(discount)::numeric min_discount,avg(discount)::numeric mean_discount,percentile_cont(0.5) WITHIN GROUP (ORDER BY discount)::numeric median_discount,max(discount)::numeric max_discount,min(current_price)::numeric min_price,avg(current_price)::numeric mean_price,percentile_cont(0.5) WITHIN GROUP (ORDER BY current_price)::numeric median_price,max(current_price)::numeric max_price FROM (${productSummary}) s`, [merchantExternalId]);
  const sizes = await rows("SELECT v.size,count(*)::int variants FROM product_variants v JOIN commerce_merchants m ON m.id=v.merchant_id WHERE m.external_merchant_id=$1 GROUP BY v.size ORDER BY variants DESC NULLS LAST", [merchantExternalId]);
  const colours = await rows("SELECT v.colour,count(*)::int variants FROM product_variants v JOIN commerce_merchants m ON m.id=v.merchant_id WHERE m.external_merchant_id=$1 GROUP BY v.colour ORDER BY variants DESC NULLS LAST", [merchantExternalId]);
  const variantStats = await one("SELECT min(n)::int min,avg(n)::numeric mean,percentile_cont(0.5) WITHIN GROUP (ORDER BY n)::numeric median,max(n)::int max,count(*) FILTER (WHERE n=1)::int single_variant,count(*) FILTER (WHERE n>1)::int multiple_variants FROM (SELECT v.product_id,count(*) n FROM product_variants v JOIN commerce_merchants m ON m.id=v.merchant_id WHERE m.external_merchant_id=$1 GROUP BY v.product_id) x", [merchantExternalId]);
  const top50 = await rows(`SELECT brand,name,category,usage_type,variants,sizes,colours,old_price,current_price,discount,images,affiliate_link_available,merchant_link_available,promotion_status,publication_state FROM (${productSummary}) s ORDER BY discount DESC,current_price,name LIMIT 50`, [merchantExternalId]);
  const secrets = await one("SELECT (SELECT count(*)::int FROM commerce_raw_feed_items r JOIN commerce_merchants m ON m.id=r.merchant_id CROSS JOIN LATERAL jsonb_object_keys(r.raw_payload) k(key) WHERE m.external_merchant_id=$1 AND k.key~*$2) forbidden_raw_keys,(SELECT count(*)::int FROM commerce_feeds f JOIN commerce_merchants m ON m.id=f.merchant_id WHERE m.external_merchant_id=$1 AND f.metadata::text~*$3) secret_feed_metadata", [merchantExternalId, "api.?key|access.?token|password|secret|feed.?url|database.?url", "api.?key|access.?token|password|secret|https?://|database.?url"]);
  process.stdout.write(`${JSON.stringify({ generatedAt: new Date().toISOString(), baseline, dafiti, providerMerchants: isolation, feeds, safety, promotionEvidence: evidence, productStats, brandDistribution, discountDistribution, priceDistribution, usageDistribution, variantStats, sizes, colours, top50, security: { ...secrets, fullUrlsSelected: false } }, null, 2)}\n`);
}

void main().finally(() => pool.end()).catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
