import pg from "pg";
import { classifyAudience, classifyDafitiScope, DAFITI_MERCHANT_ID, suspiciousSize } from "../server/integrations/awin/dafitiCuration";
import { assessSize, classifyCatalogEligibility, classifyProductTaxonomy, type ProductTaxonomyResult } from "../server/integrations/awin/productTaxonomy";

type Row=Record<string,any>;
const count=(target:Record<string,number>,key:string)=>target[key]=(target[key]??0)+1;
const percent=(n:number,d:number)=>+(n*100/Math.max(d,1)).toFixed(2);
const stats=(values:number[])=>{const a=[...values].sort((x,y)=>x-y),q=(p:number)=>a.length?a[Math.floor((a.length-1)*p)]:null;return {mean:a.length?+(a.reduce((x,y)=>x+y,0)/a.length).toFixed(2):null,median:q(.5)};};
const fold=(value:unknown)=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR");
const negative=/\b(sandalia|chinelo|rasteira|sapatilha|scarpin|bota|mocassim|oxford|sapato social|papete)\b/;
const activityText=/\b(corrida|running|runner|caminhada|walking|treino|training|academia|futebol|futsal|basquete|basketball|skate|trail|quadra|volei|volleyball|performance|sportswear|casual|lifestyle)\b/;

function old(row:Row){return classifyDafitiScope({merchantCategory:row.merchant_category,categoryPath:row.category_path,secondCategory:row.second_category,thirdCategory:row.third_category,productType:row.product_type,fashionCategory:row.fashion_category,name:row.name,description:row.description}).scope;}
function taxonomy(row:Row){return classifyProductTaxonomy({merchantCategory:row.merchant_category,categoryPath:row.category_path,secondCategory:row.second_category,thirdCategory:row.third_category,productType:row.product_type,fashionCategory:row.fashion_category,attributes:row.attributes,name:row.name,description:row.description,brand:row.brand});}
function sample(row:Row,previous:string,next:ProductTaxonomyResult,eligibility:string){return {productId:row.product_id,brand:row.brand,name:row.name,merchantCategory:row.merchant_category,oldClassification:previous,newClassification:next.universe,style:next.style,activities:next.activities,confidence:next.confidence,eligibility,reasonCodes:next.reasons};}

async function main(){
 const mode=process.argv[2]??"summary";if(!["summary","compact","brands","samples"].includes(mode))throw new Error("Uso: summary|compact|brands|samples");
 const connectionString=process.env.AWIN_CURATOR_DATABASE_URL;if(!connectionString)throw new Error("AWIN_CURATOR_DATABASE_URL é obrigatória; DATABASE_URL não é usada");
 const pool=new pg.Pool({connectionString,max:1}),client=await pool.connect();
 try{
  await client.query("BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");
  const baselineSql=`SELECT current_user,(SELECT count(*) FROM products)::int products_total,(SELECT count(*) FROM products WHERE catalog_status='published')::int published,(SELECT count(*) FROM users)::int users,(SELECT count(*) FROM user_favorites)::int favorites,(SELECT count(*) FROM external_product_identities e JOIN commerce_merchants m ON m.id=e.merchant_id WHERE m.external_merchant_id=$1)::int dafiti_products,(SELECT count(*) FROM external_product_identities e JOIN commerce_merchants m ON m.id=e.merchant_id WHERE m.external_merchant_id=$1 AND (e.publication_state<>'staging' OR e.active))::int unsafe_products,(SELECT count(*) FROM product_variants v JOIN commerce_merchants m ON m.id=v.merchant_id WHERE m.external_merchant_id=$1 AND v.active)::int active_variants,(SELECT count(*) FROM offers o JOIN commerce_merchants m ON m.id=o.merchant_id WHERE m.external_merchant_id=$1 AND (o.active OR o.status<>'paused'))::int unsafe_offers`;
  const before=(await client.query(baselineSql,[DAFITI_MERCHANT_ID])).rows[0];
  const rows=(await client.query(`SELECT p.id product_id,p.main_name name,p.detailed_description description,v.id variant_id,v.size,v.attributes,o.id offer_id,o.current_price::float8,o.original_price::float8,o.currency,o.in_stock,(o.affiliate_url IS NOT NULL AND o.affiliate_url<>'') affiliate_available,(o.original_url IS NOT NULL AND o.original_url<>'') merchant_url_available,pe.discount_percent::float8,pe.old_price::float8,pe.current_price::float8 evidence_current,r.raw_payload->>'brand_name' brand,r.raw_payload->>'merchant_category' merchant_category,r.raw_payload->>'merchant_product_category_path' category_path,r.raw_payload->>'merchant_product_second_category' second_category,r.raw_payload->>'merchant_product_third_category' third_category,r.raw_payload->>'product_type' product_type,r.raw_payload->>'Fashion:category' fashion_category,r.raw_payload->>'Fashion:suitable_for' suitable_for,(SELECT count(*)::int FROM product_images i WHERE i.product_id=p.id) image_count FROM commerce_merchants m JOIN external_product_identities e ON e.merchant_id=m.id JOIN products p ON p.id=e.product_id JOIN product_variants v ON v.product_id=p.id AND v.merchant_id=m.id JOIN offers o ON o.variant_id=v.id AND o.merchant_id=m.id JOIN offer_promotion_evidence pe ON pe.offer_id=o.id LEFT JOIN commerce_raw_feed_items r ON r.merchant_id=m.id AND r.merchant_product_id=v.merchant_product_id WHERE m.external_merchant_id=$1 ORDER BY p.id,v.id`,[DAFITI_MERCHANT_ID])).rows as Row[];
  const grouped=new Map<string,Row[]>();for(const row of rows)grouped.set(row.product_id,[...(grouped.get(row.product_id)??[]),row]);
  const universe:Record<string,number>={},styles:Record<string,number>={},activities:Record<string,number>={},confidence:Record<string,number>={},eligibilityCounts:Record<string,number>={},transition:Record<string,Record<string,number>>={},oldUncertain:Record<string,number>={},uncertainEntry={automatic:0,mediumConfidence:0,humanReview:0,out:0};
  const causeCounts:Record<string,number>={},causeExamples:Record<string,any[]>={},categoryCounts:Record<string,number>={},uncertainBrands:Record<string,number>={},terms:Record<string,number>={};
  const samples:Record<string,any[]>={SNEAKER_CONFIRMED:[],SNEAKER_PROBABLE:[],NON_SNEAKER:[],UNRESOLVED:[],CHANGED:[]},suspicious:any[]=[];
  const brandMap=new Map<string,Array<{row:Row;taxonomy:ProductTaxonomyResult;eligibility:string;discount:number}>>();
  const stop=new Set("tenis sneaker masculino feminina feminino infantil unissex para com sem de da do das dos em uma preto branco bege azul cinza rosa verde marrom".split(" "));
  for(const [id,productRows] of Array.from(grouped)){const first=productRows[0],previous=old(first),next=taxonomy(first);const good=productRows.some((r:Row)=>r.old_price>r.current_price&&r.current_price>0&&Math.abs(r.discount_percent-((r.old_price-r.current_price)/r.old_price*100))<=.11&&r.in_stock&&r.affiliate_available&&r.merchant_url_available&&r.image_count>0&&String(r.brand??"").trim()&&String(r.name??"").trim()&&String(r.size??"").trim()&&r.currency==="BRL");
    const commercial={promotionConfirmed:good,validCurrentPrice:productRows.some((r:Row)=>r.current_price>0),validOldPrice:productRows.some((r:Row)=>r.old_price>0),discountConsistent:productRows.some((r:Row)=>Math.abs(r.discount_percent-((r.old_price-r.current_price)/r.old_price*100))<=.11),imageAvailable:first.image_count>0,brandAvailable:Boolean(String(first.brand??"").trim()),affiliateAvailable:productRows.some((r:Row)=>r.affiliate_available),inStock:productRows.some((r:Row)=>r.in_stock),identitySufficient:Boolean(id)};
    const eligible=classifyCatalogEligibility(next,commercial);count(universe,next.universe);count(styles,next.style);for(const a of next.activities)count(activities,a);count(confidence,next.confidence);count(eligibilityCounts,eligible.status);transition[previous]??={};count(transition[previous],next.universe);
    const item=sample(first,previous,next,eligible.status);if(samples[next.universe].length<(next.universe.startsWith("SNEAKER")?20:20))samples[next.universe].push(item);if(previous==="UNCERTAIN"&&next.universe!=="UNRESOLVED"&&samples.CHANGED.length<20)samples.CHANGED.push(item);
    if(previous==="UNCERTAIN"){count(oldUncertain,next.universe);if(eligible.status==="IN_SCOPE_CONFIRMED")uncertainEntry.automatic++;else if(eligible.status==="IN_SCOPE_PROBABLE")uncertainEntry.mediumConfidence++;else if(eligible.status==="OUT_OF_SCOPE_CONFIRMED")uncertainEntry.out++;else uncertainEntry.humanReview++;
      const structured=fold([first.merchant_category,first.category_path,first.second_category,first.third_category,first.product_type,first.fashion_category,JSON.stringify(first.attributes??{})].join(" ")),name=fold(first.name),description=fold(first.description);const labels=[] as string[];
      labels.push("GENERIC_STRUCTURED_SNEAKER_SIGNAL");if(/\b(tenis|sneaker|sapatenis)\b/.test(name))labels.push("NAME_SNEAKER_SIGNAL");if(activityText.test(description)&&!activityText.test(`${structured} ${name}`))labels.push("DESCRIPTION_ONLY_ACTIVITY_SIGNAL");if(negative.test(`${structured} ${name}`))labels.push("CONFLICTING_NEGATIVE_FOOTWEAR_SIGNAL");if(!activityText.test(`${structured} ${name} ${description}`))labels.push("NO_STYLE_OR_ACTIVITY_SIGNAL");for(const label of labels){count(causeCounts,label);causeExamples[label]??=[];if(causeExamples[label].length<5)causeExamples[label].push(item);}count(categoryCounts,String(first.merchant_category??""));count(uncertainBrands,String(first.brand??""));for(const term of Array.from(new Set(fold(`${first.merchant_category} ${first.name}`).match(/[a-z0-9]{3,}/g)??[])))if(!stop.has(term)&&!/^\d+$/.test(term))count(terms,term);
    }
    const audience=classifyAudience({suitableFor:first.suitable_for,categoryPath:first.category_path,name:first.name});for(const row of productRows)if(suspiciousSize(row.size)){const assessment=assessSize(row.size,`${audience} ${first.name}`);if(!suspicious.some(x=>x.productId===id&&x.rawSize===row.size))suspicious.push({...item,rawSize:row.size,sizeAssessment:assessment.reason,stillSuspicious:assessment.suspicious});}
    const discount=Math.max(...productRows.map((r:Row)=>r.discount_percent));brandMap.set(String(first.brand??""),[...(brandMap.get(String(first.brand??""))??[]),{row:first,taxonomy:next,eligibility:eligible.status,discount}]);
  }
  const sorted=(record:Record<string,number>,limit=30)=>Object.entries(record).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,limit).map(([value,products])=>({value,products}));
  const brands=Array.from(brandMap).map(([brand,items])=>{const level1:Record<string,number>={},style:Record<string,number>={},activity:Record<string,number>={};for(const item of items){count(level1,item.taxonomy.universe);count(style,item.taxonomy.style);for(const a of item.taxonomy.activities)count(activity,a);}return {brand,products:items.length,discount:stats(items.map((x:{discount:number})=>x.discount)),level1,style,activity,inScopeConfirmedPercent:percent(items.filter((x:{eligibility:string})=>x.eligibility==="IN_SCOPE_CONFIRMED").length,items.length),reviewRequiredPercent:percent(items.filter((x:{eligibility:string})=>x.eligibility==="REVIEW_REQUIRED").length,items.length)};}).sort((a,b)=>b.products-a.products||a.brand.localeCompare(b.brand));
  const after=(await client.query(baselineSql,[DAFITI_MERCHANT_ID])).rows[0];
  const diagnostic={causes:sorted(causeCounts,20).map(x=>({...x,percent:percent(x.products,6046),examples:causeExamples[x.value]})),topCategories:sorted(categoryCounts),topBrands:sorted(uncertainBrands),topTerms:sorted(terms,50)};
  const regressions={oldNonUncertainToNonSneaker:Object.entries(transition).filter(([key])=>key!=="UNCERTAIN").reduce((n,[,x])=>n+(x.NON_SNEAKER??0),0),oldNonUncertainToUnresolved:Object.entries(transition).filter(([key])=>key!=="UNCERTAIN").reduce((n,[,x])=>n+(x.UNRESOLVED??0),0)};
  const summary={classifierVersion:"uppulse-taxonomy-v1",baseline:{before,after},analysed:{products:grouped.size,variants:rows.length,offers:rows.length},diagnostic,distribution:{level1:universe,style:styles,activity:activities,confidence,eligibility:eligibilityCounts},oldUncertain:{level1:oldUncertain,catalogEntry:uncertainEntry},transition,regressions,suspiciousSizes:suspicious,brandSummary:{count:brands.length,top30:brands.slice(0,30)},performance:{rowsMaterialized:rows.length,rssBytes:process.memoryUsage().rss}};
  const compact={classifierVersion:summary.classifierVersion,baseline:summary.baseline,analysed:summary.analysed,distribution:summary.distribution,oldUncertain:summary.oldUncertain,transition:summary.transition,regressions:summary.regressions,suspiciousSizes:summary.suspiciousSizes,diagnostic:{causes:summary.diagnostic.causes.map(({examples:_,...cause})=>cause),topCategories:summary.diagnostic.topCategories,topBrands:summary.diagnostic.topBrands,topTerms:summary.diagnostic.topTerms},brandCount:brands.length};
  console.log(JSON.stringify(mode==="brands"?brands:mode==="samples"?samples:mode==="compact"?compact:summary,null,2));await client.query("ROLLBACK");
 }finally{client.release();await pool.end();}
}
void main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exitCode=1;});
