import pg from "pg";

const connectionString=process.env.AWIN_CURATOR_DATABASE_URL;if(!connectionString)throw new Error("AWIN_CURATOR_DATABASE_URL_REQUIRED");
const pool=new pg.Pool({connectionString,max:1,application_name:"upcat001_1_explain"});
type Node=Record<string,any>;
function summarize(plan:Node){const nodes:Node[]=[];const walk=(n:Node)=>{nodes.push(n);for(const child of n.Plans??[])walk(child)};walk(plan.Plan);return {planningMs:plan["Planning Time"],executionMs:plan["Execution Time"],rootRows:plan.Plan["Actual Rows"],tempRead:nodes.reduce((n,x)=>n+(x["Temp Read Blocks"]??0),0),tempWritten:nodes.reduce((n,x)=>n+(x["Temp Written Blocks"]??0),0),sharedHit:nodes.reduce((n,x)=>n+(x["Shared Hit Blocks"]??0),0),sharedRead:nodes.reduce((n,x)=>n+(x["Shared Read Blocks"]??0),0),nodes:nodes.filter(x=>/Seq Scan|Index|Sort|Hash Join|Nested Loop|Aggregate/.test(x["Node Type"])).map(x=>({type:x["Node Type"],relation:x["Relation Name"],index:x["Index Name"],rows:x["Actual Rows"],loops:x["Actual Loops"],removed:x["Rows Removed by Filter"],sort:x["Sort Method"],diskKb:x["Sort Space Type"]==="Disk"?x["Sort Space Used"]:undefined})).slice(0,30)};}
const explain=async(name:string,sql:string,params:any[]=[])=>{const result=await pool.query(`EXPLAIN (ANALYZE,BUFFERS,VERBOSE,FORMAT JSON) ${sql}`,params);console.log(JSON.stringify({name,...summarize(result.rows[0]["QUERY PLAN"][0])}));};
async function main(){try{
 await explain("latest_eligible",`SELECT product_id,merchant_id,style,activities FROM latest_product_catalog_classifications WHERE operational_state='CATALOG_ELIGIBLE'`);
 await explain("raw_product",`SELECT DISTINCT ON (v.product_id) v.product_id,r.raw_payload->>'brand_name' brand,r.raw_payload->>'Fashion:suitable_for' suitable_for FROM product_variants v JOIN commerce_raw_feed_items r ON r.merchant_id=v.merchant_id AND r.merchant_product_id=v.merchant_product_id ORDER BY v.product_id,v.id`);
 await explain("representative_offer",`SELECT DISTINCT ON (o.product_id) o.product_id,o.id,o.current_price,pe.discount_percent FROM offers o JOIN offer_promotion_evidence pe ON pe.offer_id=o.id WHERE pe.promotion_status='PROMOTION_CONFIRMED' AND o.in_stock IS TRUE ORDER BY o.product_id,pe.discount_percent DESC,o.current_price,o.id`);
 await explain("default_page_and_count",`WITH representative_offer AS MATERIALIZED (SELECT DISTINCT ON(o.product_id) o.product_id,o.current_price::float8 current_price,pe.discount_percent::float8 discount_percent FROM offers o JOIN offer_promotion_evidence pe ON pe.offer_id=o.id WHERE pe.promotion_status='PROMOTION_CONFIRMED' AND o.in_stock IS TRUE ORDER BY o.product_id,pe.discount_percent DESC,o.current_price,o.id) SELECT c.product_id,count(*) OVER() total FROM latest_product_catalog_classifications c JOIN commerce_merchants m ON m.id=c.merchant_id JOIN representative_offer o ON o.product_id=c.product_id WHERE c.operational_state='CATALOG_ELIGIBLE' AND m.external_merchant_id='17697' ORDER BY o.discount_percent DESC,c.product_id LIMIT 24`);
 await explain("size_facets",`SELECT n.size_normalized,count(DISTINCT v.product_id) FROM latest_product_variant_normalizations n JOIN product_variants v ON v.id=n.variant_id JOIN latest_product_catalog_classifications c ON c.product_id=v.product_id WHERE c.operational_state='CATALOG_ELIGIBLE' AND n.size_status='NORMALIZED_SAFE' GROUP BY n.size_normalized`);
 await explain("activity_facets",`SELECT activity,count(DISTINCT c.product_id) FROM latest_product_catalog_classifications c CROSS JOIN LATERAL unnest(c.activities) activity WHERE c.operational_state='CATALOG_ELIGIBLE' GROUP BY activity`);
 const ids=(await pool.query(`SELECT product_id FROM latest_product_catalog_classifications WHERE operational_state='CATALOG_ELIGIBLE' ORDER BY product_id LIMIT 24`)).rows.map(x=>x.product_id);
 await explain("page_details",`SELECT p.id,jsonb_agg(DISTINCT jsonb_build_object('id',v.id,'sizeRaw',n.size_raw,'sizeNormalized',n.size_normalized::float8,'colorRaw',n.colour_raw,'colorNormalized',n.colour_normalized,'available',coalesce(vo.available,false))) variants,(SELECT jsonb_agg(i.url ORDER BY i.is_primary DESC,i.sort_order,i.id) FROM product_images i WHERE i.product_id=p.id) images FROM products p JOIN product_variants v ON v.product_id=p.id JOIN latest_product_variant_normalizations n ON n.variant_id=v.id LEFT JOIN LATERAL (SELECT bool_or(o.in_stock) available FROM offers o WHERE o.variant_id=v.id) vo ON true WHERE p.id=ANY($1) GROUP BY p.id`,[ids]);
}finally{await pool.end()}}
void main().catch(error=>{console.error(error instanceof Error?error.message:"EXPLAIN_FAILED");process.exitCode=1});
