import test from "node:test"; import assert from "node:assert/strict";
import { classifyAudience,classifyDafitiScope,curateVariant,priceShape,suspiciousSize } from "./dafitiCuration";

test("classifica escopo por taxonomia antes da descrição sem inventar esporte",()=>{ assert.equal(classifyDafitiScope({merchantCategory:"Tênis Performance",name:"Runner Corrida"}).scope,"RUNNING"); assert.equal(classifyDafitiScope({merchantCategory:"Tênis",name:"Modelo urbano"}).scope,"UNCERTAIN"); assert.equal(classifyDafitiScope({merchantCategory:"Camiseta",description:"para corrida"}).scope,"EXCLUDED_NON_SNEAKER"); });
test("elegibilidade exige mínimos mas não marca nem GTIN como reputação/gate extra",()=>{ const base={scope:classifyDafitiScope({merchantCategory:"Tênis",name:"Tênis casual"}),currentPrice:80,oldPrice:100,discountPercent:20,inStock:true,affiliateAvailable:true,merchantUrlAvailable:true,imageAvailable:true,brand:"Marca X",name:"Tênis",size:"39",currency:"BRL",extremeConsistent:true}; assert.equal(curateVariant(base).status,"ELIGIBLE"); assert.deepEqual(curateVariant({...base,brand:""}).reasons,["missing_brand"]); });
test("reason codes cobrem promoção, estoque, links, imagem, título, tamanho e moeda",()=>{ const x=curateVariant({scope:classifyDafitiScope({merchantCategory:"Tênis",name:"Tênis casual"}),currentPrice:100,oldPrice:90,discountPercent:0,inStock:false,affiliateAvailable:false,merchantUrlAvailable:false,imageAvailable:false,brand:"",name:"",size:"",currency:"USD"}); assert.equal(x.status,"INELIGIBLE"); for(const r of ["promotion_not_confirmed","out_of_stock","missing_affiliate_url","missing_image","missing_brand","missing_size","non_brl"]) assert.ok(x.reasons.includes(r)); });
test("detecta tamanhos suspeitos e extremos inconsistentes",()=>{ assert.equal(suspiciousSize("39"),false); assert.equal(suspiciousSize("999"),true); const b={scope:classifyDafitiScope({merchantCategory:"Tênis Performance",name:"Tênis"}),currentPrice:20,oldPrice:100,discountPercent:80,inStock:true,affiliateAvailable:true,merchantUrlAvailable:true,imageAvailable:true,brand:"X",name:"X",size:"39",currency:"BRL"}; assert.deepEqual(curateVariant(b).reasons,["extreme_discount_inconsistent"]); });
test("detecta múltiplos preços antigos, atuais e descontos",()=>{ assert.deepEqual(priceShape([{currentPrice:80,oldPrice:100,discountPercent:20},{currentPrice:70,oldPrice:110,discountPercent:36.36}]),{singlePrice:false,multipleCurrentPrices:true,multipleOldPrices:true,multipleDiscounts:true}); });
test("gênero usa sinal semântico e nunca cor",()=>{ assert.equal(classifyAudience({suitableFor:"Feminino",colour:"azul"}),"FEMININO"); assert.equal(classifyAudience({colour:"rosa"}),"UNKNOWN"); assert.equal(classifyAudience({name:"Tênis Infantil"}),"INFANTIL"); });
