import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {resolve} from "node:path";
import {assertOperationalCatalogInvariants,auditAffiliateUrl,latestClassification,mapEligibilityToOperationalState,normalizeCatalogColour,normalizeCatalogSize,validatePromotion,type OperationalCatalogProduct,type PreparedCatalogProduct} from "./operationalCatalog";
import {assertAdministrativeIdentity,persistClassifications,persistNormalizations,validatePersistenceInvocation} from "./catalogPersistence";

test("mapeia elegibilidade sem publicar",()=>{assert.equal(mapEligibilityToOperationalState("IN_SCOPE_CONFIRMED"),"CATALOG_ELIGIBLE");assert.equal(mapEligibilityToOperationalState("IN_SCOPE_PROBABLE"),"QUARANTINED");assert.equal(mapEligibilityToOperationalState("REVIEW_REQUIRED"),"QUARANTINED");assert.equal(mapEligibilityToOperationalState("OUT_OF_SCOPE_CONFIRMED"),"OUT_OF_SCOPE");});
test("migration é append-only, idempotente e oferece latest views sem ativação",()=>{const sql=readFileSync(resolve("migrations/0008_operational_catalog.sql"),"utf8");for(const required of ["product_catalog_classifications","latest_product_catalog_classifications","product_variant_normalizations","latest_product_variant_normalizations","DISTINCT ON","classifier_version","source_evidence","append-only","BEFORE UPDATE OR DELETE","uq_product_catalog_classifications_version","uq_product_variant_normalizations_version"])assert.ok(sql.includes(required));assert.doesNotMatch(sql,/UPDATE\s+products|ALTER\s+TABLE\s+offers.*active/is);});
test("seleciona classificação vigente por classified_at e created_at",()=>{const a={id:"a",classifiedAt:new Date("2026-01-01"),createdAt:new Date("2026-01-02")},b={id:"b",classifiedAt:new Date("2026-02-01"),createdAt:new Date("2026-02-01")};assert.equal(latestClassification([a,b])?.id,"b");});
test("normaliza tamanho somente quando seguro",()=>{assert.equal(normalizeCatalogSize("40 1/2").normalized,40.5);assert.equal(normalizeCatalogSize("39").status,"NORMALIZED_SAFE");assert.equal(normalizeCatalogSize("10","INFANTIL").normalized,10);assert.equal(normalizeCatalogSize("10","MASCULINO").status,"SUSPICIOUS");});
test("preserva raw-only e suspeitos de tamanho",()=>{assert.deepEqual(normalizeCatalogSize("único").normalized,null);assert.equal(normalizeCatalogSize("único").status,"RAW_ONLY");assert.equal(normalizeCatalogSize("EG").status,"SUSPICIOUS");assert.equal(normalizeCatalogSize("US 9").status,"RAW_ONLY");});
test("normaliza cor simples e composta preservando raw",()=>{assert.deepEqual(normalizeCatalogColour("Preto"),{raw:"Preto",normalized:["preto"],status:"NORMALIZED_SAFE",compound:false,reasonCode:"COLOUR_KNOWN"});const x=normalizeCatalogColour("Preto/Branco");assert.deepEqual(x.normalized,["preto","branco"]);assert.equal(x.compound,true);assert.equal(normalizeCatalogColour("Carbon X").status,"RAW_ONLY");});
test("affiliate URL permanece literal",()=>{const literal="https://www.awin1.com/cread.php?awinmid=1&awinaffid=2&p=https%3A%2F%2Fx.test";const result=auditAffiliateUrl(literal);assert.equal(result.literal,literal);assert.equal(result.valid,true);assert.equal(result.host,"www.awin1.com");});
test("valida preços e desconto sem destruir percentual merchant",()=>{assert.equal(validatePromotion({currentPrice:80,previousPrice:100,discountPercent:20,currency:"BRL"}).valid,true);assert.ok(validatePromotion({currentPrice:100,previousPrice:80,discountPercent:20,currency:"BRL"}).reasonCodes.includes("PRICE_ORDER_INVALID"));assert.ok(validatePromotion({currentPrice:80,previousPrice:100,discountPercent:10,currency:"BRL"}).reasonCodes.includes("DISCOUNT_MATH_INCONSISTENT"));});
test("DTO contém taxonomia, variants, merchant, literal affiliate e ausência de popularidade",()=>{const dto:OperationalCatalogProduct={id:"p",brand:"X",name:"Tênis",description:null,audience:"UNISSEX",catalogStatus:"CATALOG_ELIGIBLE",taxonomy:{universe:"SNEAKER_CONFIRMED",style:"LIFESTYLE",activities:["GENERAL","WALKING"],confidence:"HIGH",reasonCodes:[],classifierVersion:"v1"},pricing:{currentPrice:80,previousPrice:100,discountPercent:20,merchantDiscountPercent:20,currency:"BRL",promotionEvidence:"feed"},variants:[{id:"v",merchantVariationIdentity:"mv",sizeRaw:"40 1/2",sizeNormalized:40.5,sizeStatus:"NORMALIZED_SAFE",colorRaw:"Preto/Branco",colorNormalized:["preto","branco"],colorStatus:"NORMALIZED_SAFE",available:true}],images:[{url:"https://img.test/x",position:0,primary:true}],merchant:{id:"m",name:"Merchant",provider:"awin"},affiliateUrl:"https://awin.test/literal",merchantUrl:null,sorting:{price:true,discount:true,brand:true,activity:true,merchant:true,relevance:false,popularity:false}};assert.equal(dto.taxonomy.activities.length,2);assert.equal(dto.sorting.popularity,false);});
const prepared=(id:string,state:PreparedCatalogProduct["state"],overrides:Partial<PreparedCatalogProduct>={}):PreparedCatalogProduct=>({id,state,validOffers:1,images:1,affiliateUrls:1,variants:1,published:false,activeVariant:false,activeOffer:false,...overrides});
test("invariantes aceitam fechamento e rejeitam Product sem Offer/imagem",()=>{const ok=[prepared("e","CATALOG_ELIGIBLE"),prepared("q","QUARANTINED"),prepared("o","OUT_OF_SCOPE")];assert.doesNotThrow(()=>assertOperationalCatalogInvariants(ok,3,{CATALOG_ELIGIBLE:1,QUARANTINED:1,OUT_OF_SCOPE:1}));assert.throws(()=>assertOperationalCatalogInvariants([prepared("e","CATALOG_ELIGIBLE",{validOffers:0})],1,{CATALOG_ELIGIBLE:1,QUARANTINED:0,OUT_OF_SCOPE:0}),/ELIGIBLE_MINIMUM/);assert.throws(()=>assertOperationalCatalogInvariants([prepared("e","CATALOG_ELIGIBLE",{images:0})],1,{CATALOG_ELIGIBLE:1,QUARANTINED:0,OUT_OF_SCOPE:0}),/ELIGIBLE_MINIMUM/);});
test("invariantes impedem quarentena/out-of-scope no elegível e qualquer visibilidade",()=>{assert.throws(()=>assertOperationalCatalogInvariants([prepared("q","QUARANTINED")],1,{CATALOG_ELIGIBLE:1,QUARANTINED:0,OUT_OF_SCOPE:0}),/EDITORIAL_CLOSURE/);assert.throws(()=>assertOperationalCatalogInvariants([prepared("e","CATALOG_ELIGIBLE",{activeOffer:true})],1,{CATALOG_ELIGIBLE:1,QUARANTINED:0,OUT_OF_SCOPE:0}),/VISIBILITY/);});
test("CLI exige conexão explícita, staging, confirmação, merchant e versões",()=>{const env={AWIN_CATALOG_ADMIN_DATABASE_URL:"postgres://admin:secret@db.example.test/postgres",AWIN_CATALOG_EXPECTED_HOST:"db.example.test"};assert.throws(()=>validatePersistenceInvocation([],env),/CONFIRMATION/);assert.throws(()=>validatePersistenceInvocation(["--mode=staging","--confirm-staging","--merchant=999","--classifier-version=v1","--normalizer-version=n1"],env),/DAFITI_MERCHANT/);const config=validatePersistenceInvocation(["--mode=staging","--confirm-staging","--merchant=17697","--classifier-version=v1","--normalizer-version=n1"],env);assert.equal(config.merchant,"17697");assert.throws(()=>assertAdministrativeIdentity({currentUser:"awin_curator",currentDatabase:"postgres"},config),/CURATOR/);});
test("CLI rejeita host administrativo divergente e não usa DATABASE_URL implícita",()=>{const args=["--mode=staging","--confirm-staging","--merchant=17697","--classifier-version=v1","--normalizer-version=n1"];assert.throws(()=>validatePersistenceInvocation(args,{DATABASE_URL:"postgres://x@y/postgres",AWIN_CATALOG_EXPECTED_HOST:"y"}),/ADMIN_DATABASE_URL_REQUIRED/);assert.throws(()=>validatePersistenceInvocation(args,{AWIN_CATALOG_ADMIN_DATABASE_URL:"postgres://x@wrong/postgres",AWIN_CATALOG_EXPECTED_HOST:"right"}),/HOST_MISMATCH/);});
test("repository contabiliza primeira carga e reimport idêntico sem UPDATE",async()=>{let insertCalls=0;const client={query:async(sql:string)=>{if(sql.includes("SELECT count(*)"))return {rows:[{count:0}],rowCount:1};insertCalls++;return {rows:[],rowCount:insertCalls===1?1:0};}} as any;const classification={productId:"p",providerId:"cp",merchantId:"m",universe:"SNEAKER_CONFIRMED" as const,style:"LIFESTYLE" as const,activities:["GENERAL" as const],confidence:"HIGH" as const,reasonCodes:[],operationalState:"CATALOG_ELIGIBLE" as const,classifierVersion:"v1",classifiedAt:"2026-08-25T00:00:00Z",sourceEvidence:{}};assert.deepEqual(await persistClassifications(client,[classification]),{seen:1,created:1,unchanged:0,invalid:0});assert.deepEqual(await persistClassifications(client,[classification]),{seen:1,created:0,unchanged:1,invalid:0});const normalization={variantId:"v",sizeRaw:"40",sizeNormalized:40,sizeStatus:"NORMALIZED_SAFE" as const,colourRaw:"Preto",colourNormalized:["preto"],colourStatus:"NORMALIZED_SAFE" as const,normalizerVersion:"n1",normalizedAt:"2026-08-25T00:00:00Z",reasonCodes:[]};assert.deepEqual(await persistNormalizations(client,[normalization]),{seen:1,created:0,unchanged:1,invalid:0});});
